/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using AdGuard.ApiClient.Client;
using AdGuard.ApiClient.Model;

namespace AdGuard.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DNSServersApi : IDisposable, IDNSServersApi
    {
        private AdGuard.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DNSServersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DNSServersApi(string basePath)
        {
            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                new AdGuard.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DNSServersApi(AdGuard.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DNSServersApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DNSServersApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                new AdGuard.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DNSServersApi(HttpClient client, AdGuard.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DNSServersApi(AdGuard.ApiClient.Client.ISynchronousClient client, AdGuard.ApiClient.Client.IAsynchronousClient asyncClient, AdGuard.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public AdGuard.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AdGuard.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AdGuard.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AdGuard.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AdGuard.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings via the request body; otherwise the server will be created with default settings. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <returns>DNSServer</returns>
        public DNSServer CreateDNSServer(DNSServerCreate dNSServerCreate)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServer> localVarResponse = CreateDNSServerWithHttpInfo(dNSServerCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings via the request body; otherwise the server will be created with default settings. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <returns>ApiResponse of DNSServer</returns>
        public AdGuard.ApiClient.Client.ApiResponse<DNSServer> CreateDNSServerWithHttpInfo(DNSServerCreate dNSServerCreate)
        {
            // verify the required parameter 'dNSServerCreate' is set
            if (dNSServerCreate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerCreate' when calling DNSServersApi->CreateDNSServer");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = dNSServerCreate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DNSServer>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings via the request body; otherwise the server will be created with default settings. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DNSServer</returns>
        public async System.Threading.Tasks.Task<DNSServer> CreateDNSServerAsync(DNSServerCreate dNSServerCreate, System.Threading.CancellationToken cancellationToken = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServer> localVarResponse = await CreateDNSServerWithHttpInfoAsync(dNSServerCreate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings via the request body; otherwise the server will be created with default settings. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DNSServer)</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<DNSServer>> CreateDNSServerWithHttpInfoAsync(DNSServerCreate dNSServerCreate, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dNSServerCreate' is set
            if (dNSServerCreate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerCreate' when calling DNSServersApi->CreateDNSServer");


            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = dNSServerCreate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<DNSServer>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a DNS server by ID Returns details of a specific DNS server. Use this endpoint to retrieve DNS server configuration including its linked devices. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <returns>DNSServer</returns>
        public DNSServer GetDNSServer(string dnsServerId)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServer> localVarResponse = GetDNSServerWithHttpInfo(dnsServerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a DNS server by ID Returns details of a specific DNS server. Use this endpoint to retrieve DNS server configuration including its linked devices. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <returns>ApiResponse of DNSServer</returns>
        public AdGuard.ApiClient.Client.ApiResponse<DNSServer> GetDNSServerWithHttpInfo(string dnsServerId)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->GetDNSServer");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DNSServer>("/oapi/v1/dns_servers/{dns_server_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets a DNS server by ID Returns details of a specific DNS server. Use this endpoint to retrieve DNS server configuration including its linked devices. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DNSServer</returns>
        public async System.Threading.Tasks.Task<DNSServer> GetDNSServerAsync(string dnsServerId, System.Threading.CancellationToken cancellationToken = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServer> localVarResponse = await GetDNSServerWithHttpInfoAsync(dnsServerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets a DNS server by ID Returns details of a specific DNS server. Use this endpoint to retrieve DNS server configuration including its linked devices. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DNSServer)</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<DNSServer>> GetDNSServerWithHttpInfoAsync(string dnsServerId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->GetDNSServer");


            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DNSServer>("/oapi/v1/dns_servers/{dns_server_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets DNS server settings Returns the current settings of a DNS server, including filtering, parental control, and access configuration. Use this endpoint to review the current configuration before making changes. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <returns>DNSServerSettings</returns>
        public DNSServerSettings GetDNSServerSettings(string dnsServerId)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServerSettings> localVarResponse = GetDNSServerSettingsWithHttpInfo(dnsServerId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets DNS server settings Returns the current settings of a DNS server, including filtering, parental control, and access configuration. Use this endpoint to review the current configuration before making changes. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <returns>ApiResponse of DNSServerSettings</returns>
        public AdGuard.ApiClient.Client.ApiResponse<DNSServerSettings> GetDNSServerSettingsWithHttpInfo(string dnsServerId)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->GetDNSServerSettings");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DNSServerSettings>("/oapi/v1/dns_servers/{dns_server_id}/settings", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDNSServerSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets DNS server settings Returns the current settings of a DNS server, including filtering, parental control, and access configuration. Use this endpoint to review the current configuration before making changes. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DNSServerSettings</returns>
        public async System.Threading.Tasks.Task<DNSServerSettings> GetDNSServerSettingsAsync(string dnsServerId, System.Threading.CancellationToken cancellationToken = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServerSettings> localVarResponse = await GetDNSServerSettingsWithHttpInfoAsync(dnsServerId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets DNS server settings Returns the current settings of a DNS server, including filtering, parental control, and access configuration. Use this endpoint to review the current configuration before making changes. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DNSServerSettings)</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<DNSServerSettings>> GetDNSServerSettingsWithHttpInfoAsync(string dnsServerId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->GetDNSServerSettings");


            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DNSServerSettings>("/oapi/v1/dns_servers/{dns_server_id}/settings", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDNSServerSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Lists DNS servers Lists DNS servers according to the specified parameters. By default there is at least one default server. Response is paginated, items are arranged in the newest-first order. For the initial request a default limit is applied if not specified. For the subsequent requests cursor must be provided (limit can be omitted). Filtering parameters, if specified for the initial request, must be provided on each page request as well. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="limit">Pagination limit (may be overridden by cursor) (optional, default to 10)</param>
        /// <param name="dnsServers">Filter by DNS servers (optional)</param>
        /// <param name="search">Search by DNS server name or ID (optional)</param>
        /// <returns>DnsServersResponse</returns>
        public DnsServersResponse GetDnsServers(string? cursor = default, int? limit = default, List<string>? dnsServers = default, string? search = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<DnsServersResponse> localVarResponse = GetDnsServersWithHttpInfo(cursor, limit, dnsServers, search);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Lists DNS servers Lists DNS servers according to the specified parameters. By default there is at least one default server. Response is paginated, items are arranged in the newest-first order. For the initial request a default limit is applied if not specified. For the subsequent requests cursor must be provided (limit can be omitted). Filtering parameters, if specified for the initial request, must be provided on each page request as well. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="limit">Pagination limit (may be overridden by cursor) (optional, default to 10)</param>
        /// <param name="dnsServers">Filter by DNS servers (optional)</param>
        /// <param name="search">Search by DNS server name or ID (optional)</param>
        /// <returns>ApiResponse of DnsServersResponse</returns>
        public AdGuard.ApiClient.Client.ApiResponse<DnsServersResponse> GetDnsServersWithHttpInfo(string? cursor = default, int? limit = default, List<string>? dnsServers = default, string? search = default)
        {
            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (dnsServers != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("multi", "dns_servers", dnsServers));
            }
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DnsServersResponse>("/oapi/v2/dns_servers", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDnsServers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Lists DNS servers Lists DNS servers according to the specified parameters. By default there is at least one default server. Response is paginated, items are arranged in the newest-first order. For the initial request a default limit is applied if not specified. For the subsequent requests cursor must be provided (limit can be omitted). Filtering parameters, if specified for the initial request, must be provided on each page request as well. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="limit">Pagination limit (may be overridden by cursor) (optional, default to 10)</param>
        /// <param name="dnsServers">Filter by DNS servers (optional)</param>
        /// <param name="search">Search by DNS server name or ID (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DnsServersResponse</returns>
        public async System.Threading.Tasks.Task<DnsServersResponse> GetDnsServersAsync(string? cursor = default, int? limit = default, List<string>? dnsServers = default, string? search = default, System.Threading.CancellationToken cancellationToken = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<DnsServersResponse> localVarResponse = await GetDnsServersWithHttpInfoAsync(cursor, limit, dnsServers, search, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Lists DNS servers Lists DNS servers according to the specified parameters. By default there is at least one default server. Response is paginated, items are arranged in the newest-first order. For the initial request a default limit is applied if not specified. For the subsequent requests cursor must be provided (limit can be omitted). Filtering parameters, if specified for the initial request, must be provided on each page request as well. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cursor">Pagination cursor (optional)</param>
        /// <param name="limit">Pagination limit (may be overridden by cursor) (optional, default to 10)</param>
        /// <param name="dnsServers">Filter by DNS servers (optional)</param>
        /// <param name="search">Search by DNS server name or ID (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DnsServersResponse)</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<DnsServersResponse>> GetDnsServersWithHttpInfoAsync(string? cursor = default, int? limit = default, List<string>? dnsServers = default, string? search = default, System.Threading.CancellationToken cancellationToken = default)
        {

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (dnsServers != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("multi", "dns_servers", dnsServers));
            }
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(AdGuard.ApiClient.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DnsServersResponse>("/oapi/v2/dns_servers", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDnsServers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Lists DNS servers Method is deprecated and scheduled for removal in January 2027. Use the /oapi/v2 version instead.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;DNSServer&gt;</returns>
        [Obsolete]
        public List<DNSServer> ListDNSServers()
        {
            AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>> localVarResponse = ListDNSServersWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Lists DNS servers Method is deprecated and scheduled for removal in January 2027. Use the /oapi/v2 version instead.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;DNSServer&gt;</returns>
        [Obsolete]
        public AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>> ListDNSServersWithHttpInfo()
        {
            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<DNSServer>>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDNSServers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Lists DNS servers Method is deprecated and scheduled for removal in January 2027. Use the /oapi/v2 version instead.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DNSServer&gt;</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<List<DNSServer>> ListDNSServersAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>> localVarResponse = await ListDNSServersWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Lists DNS servers Method is deprecated and scheduled for removal in January 2027. Use the /oapi/v2 version instead.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DNSServer&gt;)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>>> ListDNSServersWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<DNSServer>>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDNSServers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Removes a DNS server Removes a DNS server. All devices attached to this DNS server will be moved to the default DNS server. Deleting the default DNS server is forbidden. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <returns></returns>
        public void RemoveDNSServer(string dnsServerId)
        {
            RemoveDNSServerWithHttpInfo(dnsServerId);
        }

        /// <summary>
        /// Removes a DNS server Removes a DNS server. All devices attached to this DNS server will be moved to the default DNS server. Deleting the default DNS server is forbidden. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AdGuard.ApiClient.Client.ApiResponse<Object> RemoveDNSServerWithHttpInfo(string dnsServerId)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->RemoveDNSServer");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/oapi/v1/dns_servers/{dns_server_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Removes a DNS server Removes a DNS server. All devices attached to this DNS server will be moved to the default DNS server. Deleting the default DNS server is forbidden. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task RemoveDNSServerAsync(string dnsServerId, System.Threading.CancellationToken cancellationToken = default)
        {
            await RemoveDNSServerWithHttpInfoAsync(dnsServerId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Removes a DNS server Removes a DNS server. All devices attached to this DNS server will be moved to the default DNS server. Deleting the default DNS server is forbidden. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<Object>> RemoveDNSServerWithHttpInfoAsync(string dnsServerId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->RemoveDNSServer");


            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/oapi/v1/dns_servers/{dns_server_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates a DNS server Updates a DNS server with the provided fields. Only the specified fields will be modified. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerUpdate"></param>
        /// <returns></returns>
        public void UpdateDNSServer(string dnsServerId, DNSServerUpdate dNSServerUpdate)
        {
            UpdateDNSServerWithHttpInfo(dnsServerId, dNSServerUpdate);
        }

        /// <summary>
        /// Updates a DNS server Updates a DNS server with the provided fields. Only the specified fields will be modified. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerUpdate"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AdGuard.ApiClient.Client.ApiResponse<Object> UpdateDNSServerWithHttpInfo(string dnsServerId, DNSServerUpdate dNSServerUpdate)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->UpdateDNSServer");

            // verify the required parameter 'dNSServerUpdate' is set
            if (dNSServerUpdate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerUpdate' when calling DNSServersApi->UpdateDNSServer");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter
            localVarRequestOptions.Data = dNSServerUpdate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/oapi/v1/dns_servers/{dns_server_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates a DNS server Updates a DNS server with the provided fields. Only the specified fields will be modified. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerUpdate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UpdateDNSServerAsync(string dnsServerId, DNSServerUpdate dNSServerUpdate, System.Threading.CancellationToken cancellationToken = default)
        {
            await UpdateDNSServerWithHttpInfoAsync(dnsServerId, dNSServerUpdate, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Updates a DNS server Updates a DNS server with the provided fields. Only the specified fields will be modified. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerUpdate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<Object>> UpdateDNSServerWithHttpInfoAsync(string dnsServerId, DNSServerUpdate dNSServerUpdate, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->UpdateDNSServer");

            // verify the required parameter 'dNSServerUpdate' is set
            if (dNSServerUpdate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerUpdate' when calling DNSServersApi->UpdateDNSServer");


            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter
            localVarRequestOptions.Data = dNSServerUpdate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/oapi/v1/dns_servers/{dns_server_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings of a DNS server, such as filtering, parental control, and access configuration. Provide the settings to update in the request body. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerSettingsUpdate"></param>
        /// <returns></returns>
        public void UpdateDNSServerSettings(string dnsServerId, DNSServerSettingsUpdate dNSServerSettingsUpdate)
        {
            UpdateDNSServerSettingsWithHttpInfo(dnsServerId, dNSServerSettingsUpdate);
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings of a DNS server, such as filtering, parental control, and access configuration. Provide the settings to update in the request body. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerSettingsUpdate"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AdGuard.ApiClient.Client.ApiResponse<Object> UpdateDNSServerSettingsWithHttpInfo(string dnsServerId, DNSServerSettingsUpdate dNSServerSettingsUpdate)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->UpdateDNSServerSettings");

            // verify the required parameter 'dNSServerSettingsUpdate' is set
            if (dNSServerSettingsUpdate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerSettingsUpdate' when calling DNSServersApi->UpdateDNSServerSettings");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter
            localVarRequestOptions.Data = dNSServerSettingsUpdate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/oapi/v1/dns_servers/{dns_server_id}/settings", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDNSServerSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings of a DNS server, such as filtering, parental control, and access configuration. Provide the settings to update in the request body. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerSettingsUpdate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UpdateDNSServerSettingsAsync(string dnsServerId, DNSServerSettingsUpdate dNSServerSettingsUpdate, System.Threading.CancellationToken cancellationToken = default)
        {
            await UpdateDNSServerSettingsWithHttpInfoAsync(dnsServerId, dNSServerSettingsUpdate, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings of a DNS server, such as filtering, parental control, and access configuration. Provide the settings to update in the request body. 
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId"></param>
        /// <param name="dNSServerSettingsUpdate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<Object>> UpdateDNSServerSettingsWithHttpInfoAsync(string dnsServerId, DNSServerSettingsUpdate dNSServerSettingsUpdate, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->UpdateDNSServerSettings");

            // verify the required parameter 'dNSServerSettingsUpdate' is set
            if (dNSServerSettingsUpdate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerSettingsUpdate' when calling DNSServersApi->UpdateDNSServerSettings");


            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId)); // path parameter
            localVarRequestOptions.Data = dNSServerSettingsUpdate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/oapi/v1/dns_servers/{dns_server_id}/settings", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDNSServerSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
