/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`access_token`]
#[derive(Clone, Debug)]
pub struct AccessTokenParams {
    /// OAuth2 grant type. Accepted values: \\\"password\\\", \\\"refresh_token\\\", \\\"authorization_code\\\". Required for Authorization Code + PKCE flow.
    pub grant_type: String,
    /// OAuth2 client identifier
    pub client_id: Option<String>,
    /// Authorization code received from the authorization server
    pub code: Option<String>,
    /// PKCE code verifier (43-128 chars)
    pub code_verifier: Option<String>,
    /// Two-Factor authentication token (if enabled in account settings)
    pub mfa_token: Option<String>,
    /// Account password
    pub password: Option<String>,
    /// Redirect URI used in the authorization request
    pub redirect_uri: Option<String>,
    /// Refresh token
    pub refresh_token: Option<String>,
    /// Account email
    pub username: Option<String>
}

/// struct for passing parameters to the method [`authorize`]
#[derive(Clone, Debug)]
pub struct AuthorizeParams {
    /// OAuth2 client identifier
    pub client_id: String,
    /// Type of grant. Use response_type=token for Implicit grant, response_type=code for Authorization Code + PKCE flow
    pub response_type: String,
    /// A successful response results in a redirect to this URL
    pub redirect_uri: String,
    /// An opaque value, used for security purposes
    pub state: Option<String>,
    /// Affiliate identifier
    pub aid: Option<String>,
    /// Affiliate source
    pub source: Option<String>,
    /// PKCE code challenge: BASE64URL(SHA256(code_verifier)). Required for Authorization Code + PKCE flow
    pub code_challenge: Option<String>,
    /// PKCE challenge method. Only \"S256\" is supported
    pub code_challenge_method: Option<String>
}

/// struct for passing parameters to the method [`revoke_token`]
#[derive(Clone, Debug)]
pub struct RevokeTokenParams {
    /// Refresh token to revoke
    pub refresh_token: String
}


/// struct for typed errors of method [`access_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AccessTokenError {
    Status400(models::ErrorResponse),
    Status401(models::AccessTokenErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`authorize`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AuthorizeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`revoke_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeTokenError {
    UnknownValue(serde_json::Value),
}


/// Obtains an access token using one of three grant types:  **1. Password + optional 2FA** (`grant_type=password`): Provide `username` and `password`. If two-factor authentication is enabled on the account, also provide `mfa_token`.  **2. Refresh token** (`grant_type=refresh_token`): Provide `refresh_token` to exchange it for a new access token without re-entering credentials.  **3. Authorization Code + PKCE** (`grant_type=authorization_code`): Exchange an authorization code obtained via the `/oauth_authorize` endpoint. Provide `code`, `client_id`, `code_verifier`, and `redirect_uri`. 
pub async fn access_token(configuration: &configuration::Configuration, params: AccessTokenParams) -> Result<models::AccessTokenResponse, Error<AccessTokenError>> {

    let uri_str = format!("{}/oapi/v1/oauth_token", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = std::collections::HashMap::new();
    if let Some(param_value) = params.client_id {
        multipart_form_params.insert("client_id", param_value.to_string());
    }
    if let Some(param_value) = params.code {
        multipart_form_params.insert("code", param_value.to_string());
    }
    if let Some(param_value) = params.code_verifier {
        multipart_form_params.insert("code_verifier", param_value.to_string());
    }
    multipart_form_params.insert("grant_type", params.grant_type.to_string());
    if let Some(param_value) = params.mfa_token {
        multipart_form_params.insert("mfa_token", param_value.to_string());
    }
    if let Some(param_value) = params.password {
        multipart_form_params.insert("password", param_value.to_string());
    }
    if let Some(param_value) = params.redirect_uri {
        multipart_form_params.insert("redirect_uri", param_value.to_string());
    }
    if let Some(param_value) = params.refresh_token {
        multipart_form_params.insert("refresh_token", param_value.to_string());
    }
    if let Some(param_value) = params.username {
        multipart_form_params.insert("username", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AccessTokenResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AccessTokenResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AccessTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Initiates an OAuth2 authorization flow by redirecting the user to the AdGuard authorization server.  Use `response_type=token` for the Implicit grant or `response_type=code` together with `code_challenge` and `code_challenge_method=S256` for the Authorization Code + PKCE flow.  On success the authorization server redirects back to `redirect_uri`. For the Implicit grant the access token is embedded in the URL fragment (`#access_token=...`). For the Authorization Code flow a one-time `code` is appended as a query parameter and must be exchanged for tokens via the `/oauth_token` endpoint. 
pub async fn authorize(configuration: &configuration::Configuration, params: AuthorizeParams) -> Result<(), Error<AuthorizeError>> {

    let uri_str = format!("{}/oapi/v1/oauth_authorize", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("client_id", &params.client_id.to_string())]);
    req_builder = req_builder.query(&[("response_type", &params.response_type.to_string())]);
    req_builder = req_builder.query(&[("redirect_uri", &params.redirect_uri.to_string())]);
    if let Some(ref param_value) = params.state {
        req_builder = req_builder.query(&[("state", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.aid {
        req_builder = req_builder.query(&[("aid", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.source {
        req_builder = req_builder.query(&[("source", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.code_challenge {
        req_builder = req_builder.query(&[("code_challenge", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.code_challenge_method {
        req_builder = req_builder.query(&[("code_challenge_method", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<AuthorizeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Permanently invalidates a refresh token. After revocation the token cannot be used to obtain new access tokens. Revoke the refresh token when the user logs out or when you suspect the token has been compromised. 
pub async fn revoke_token(configuration: &configuration::Configuration, params: RevokeTokenParams) -> Result<(), Error<RevokeTokenError>> {

    let uri_str = format!("{}/oapi/v1/revoke_token", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("refresh_token", &params.refresh_token.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RevokeTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

