/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Blocked filtering category update action
    /// </summary>
    [DataContract(Name = "BlockedFilteringCategoryUpdate")]
    public partial class BlockedFilteringCategoryUpdate
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockedFilteringCategoryUpdate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BlockedFilteringCategoryUpdate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockedFilteringCategoryUpdate" /> class.
        /// </summary>
        /// <param name="enabled">Whether category blocking is enabled.</param>
        /// <param name="id">Category identifier (required).</param>
        public BlockedFilteringCategoryUpdate(bool enabled = default, string id = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for BlockedFilteringCategoryUpdate and cannot be null");
            }
            this.Id = id;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Whether category blocking is enabled
        /// </summary>
        /// <value>Whether category blocking is enabled</value>
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Category identifier
        /// </summary>
        /// <value>Category identifier</value>
        /*
        <example>adult</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BlockedFilteringCategoryUpdate {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
