/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Blocking mode
    /// </summary>
    /// <value>Blocking mode</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BlockingMode
    {
        /// <summary>
        /// Enum NONE for value: NONE
        /// </summary>
        [EnumMember(Value = "NONE")]
        NONE = 1,

        /// <summary>
        /// Enum NULLIP for value: NULL_IP
        /// </summary>
        [EnumMember(Value = "NULL_IP")]
        NULLIP = 2,

        /// <summary>
        /// Enum REFUSED for value: REFUSED
        /// </summary>
        [EnumMember(Value = "REFUSED")]
        REFUSED = 3,

        /// <summary>
        /// Enum NXDOMAIN for value: NXDOMAIN
        /// </summary>
        [EnumMember(Value = "NXDOMAIN")]
        NXDOMAIN = 4,

        /// <summary>
        /// Enum CUSTOMIP for value: CUSTOM_IP
        /// </summary>
        [EnumMember(Value = "CUSTOM_IP")]
        CUSTOMIP = 5
    }

}
