/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Category query statistics list
    /// </summary>
    [DataContract(Name = "CategoryQueriesStatsList")]
    public partial class CategoryQueriesStatsList
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoryQueriesStatsList" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CategoryQueriesStatsList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CategoryQueriesStatsList" /> class.
        /// </summary>
        /// <param name="stats">List of queries stats (required).</param>
        public CategoryQueriesStatsList(List<CategoryQueriesStats> stats = default)
        {
            // to ensure "stats" is required (not null)
            if (stats == null)
            {
                throw new ArgumentNullException("stats is a required property for CategoryQueriesStatsList and cannot be null");
            }
            this.Stats = stats;
        }

        /// <summary>
        /// List of queries stats
        /// </summary>
        /// <value>List of queries stats</value>
        [DataMember(Name = "stats", IsRequired = true, EmitDefaultValue = true)]
        public List<CategoryQueriesStats> Stats { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CategoryQueriesStatsList {\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
