/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Company detailed queries statistics
    /// </summary>
    [DataContract(Name = "CompanyDetailedQueriesStatsList")]
    public partial class CompanyDetailedQueriesStatsList
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyDetailedQueriesStatsList" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompanyDetailedQueriesStatsList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyDetailedQueriesStatsList" /> class.
        /// </summary>
        /// <param name="navigation">navigation (required).</param>
        /// <param name="pages">Pagination. Field is deprecated and scheduled for removal in January 2027. Use &#x60;navigation&#x60; instead.</param>
        /// <param name="stats">List of queries stats (required).</param>
        public CompanyDetailedQueriesStatsList(Navigation navigation = default, List<Page> pages = default, List<CompanyDetailedQueriesStats> stats = default)
        {
            // to ensure "navigation" is required (not null)
            if (navigation == null)
            {
                throw new ArgumentNullException("navigation is a required property for CompanyDetailedQueriesStatsList and cannot be null");
            }
            this.Navigation = navigation;
            // to ensure "stats" is required (not null)
            if (stats == null)
            {
                throw new ArgumentNullException("stats is a required property for CompanyDetailedQueriesStatsList and cannot be null");
            }
            this.Stats = stats;
            this.Pages = pages;
        }

        /// <summary>
        /// Gets or Sets Navigation
        /// </summary>
        [DataMember(Name = "navigation", IsRequired = true, EmitDefaultValue = true)]
        public Navigation Navigation { get; set; }

        /// <summary>
        /// Pagination. Field is deprecated and scheduled for removal in January 2027. Use &#x60;navigation&#x60; instead
        /// </summary>
        /// <value>Pagination. Field is deprecated and scheduled for removal in January 2027. Use &#x60;navigation&#x60; instead</value>
        [DataMember(Name = "pages", EmitDefaultValue = false)]
        [Obsolete]
        public List<Page> Pages { get; set; }

        /// <summary>
        /// List of queries stats
        /// </summary>
        /// <value>List of queries stats</value>
        [DataMember(Name = "stats", IsRequired = true, EmitDefaultValue = true)]
        public List<CompanyDetailedQueriesStats> Stats { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompanyDetailedQueriesStatsList {\n");
            sb.Append("  Navigation: ").Append(Navigation).Append("\n");
            sb.Append("  Pages: ").Append(Pages).Append("\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
