/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Country queries stats
    /// </summary>
    [DataContract(Name = "CountryQueriesStats")]
    public partial class CountryQueriesStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CountryQueriesStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CountryQueriesStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CountryQueriesStats" /> class.
        /// </summary>
        /// <param name="country">Country code (required).</param>
        /// <param name="value">value (required).</param>
        public CountryQueriesStats(string country = default, QueriesStats value = default)
        {
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for CountryQueriesStats and cannot be null");
            }
            this.Country = country;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for CountryQueriesStats and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// Country code
        /// </summary>
        /// <value>Country code</value>
        /*
        <example>US</example>
        */
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public QueriesStats Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CountryQueriesStats {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
