/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Day of week
    /// </summary>
    /// <value>Day of week</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DayOfWeek
    {
        /// <summary>
        /// Enum MONDAY for value: MONDAY
        /// </summary>
        [EnumMember(Value = "MONDAY")]
        MONDAY = 1,

        /// <summary>
        /// Enum TUESDAY for value: TUESDAY
        /// </summary>
        [EnumMember(Value = "TUESDAY")]
        TUESDAY = 2,

        /// <summary>
        /// Enum WEDNESDAY for value: WEDNESDAY
        /// </summary>
        [EnumMember(Value = "WEDNESDAY")]
        WEDNESDAY = 3,

        /// <summary>
        /// Enum THURSDAY for value: THURSDAY
        /// </summary>
        [EnumMember(Value = "THURSDAY")]
        THURSDAY = 4,

        /// <summary>
        /// Enum FRIDAY for value: FRIDAY
        /// </summary>
        [EnumMember(Value = "FRIDAY")]
        FRIDAY = 5,

        /// <summary>
        /// Enum SATURDAY for value: SATURDAY
        /// </summary>
        [EnumMember(Value = "SATURDAY")]
        SATURDAY = 6,

        /// <summary>
        /// Enum SUNDAY for value: SUNDAY
        /// </summary>
        [EnumMember(Value = "SUNDAY")]
        SUNDAY = 7
    }

}
