/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Dedicated IPv4 address
    /// </summary>
    [DataContract(Name = "DedicatedIPv4Address")]
    public partial class DedicatedIPv4Address
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DedicatedIPv4Address" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DedicatedIPv4Address() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DedicatedIPv4Address" /> class.
        /// </summary>
        /// <param name="deviceId">Linked device ID, or null if address is vacant.</param>
        /// <param name="ip">IP address (required).</param>
        public DedicatedIPv4Address(string deviceId = default, string ip = default)
        {
            // to ensure "ip" is required (not null)
            if (ip == null)
            {
                throw new ArgumentNullException("ip is a required property for DedicatedIPv4Address and cannot be null");
            }
            this.Ip = ip;
            this.DeviceId = deviceId;
        }

        /// <summary>
        /// Linked device ID, or null if address is vacant
        /// </summary>
        /// <value>Linked device ID, or null if address is vacant</value>
        /*
        <example>b3e82cd1</example>
        */
        [DataMember(Name = "device_id", EmitDefaultValue = false)]
        public string DeviceId { get; set; }

        /// <summary>
        /// IP address
        /// </summary>
        /// <value>IP address</value>
        /*
        <example>94.140.14.15</example>
        */
        [DataMember(Name = "ip", IsRequired = true, EmitDefaultValue = true)]
        public string Ip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DedicatedIPv4Address {\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
