/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS proto response type
    /// </summary>
    /// <value>DNS proto response type</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DnsProtoResponseType
    {
        /// <summary>
        /// Enum RcodeSuccess for value: RcodeSuccess
        /// </summary>
        [EnumMember(Value = "RcodeSuccess")]
        RcodeSuccess = 1,

        /// <summary>
        /// Enum RcodeFormatError for value: RcodeFormatError
        /// </summary>
        [EnumMember(Value = "RcodeFormatError")]
        RcodeFormatError = 2,

        /// <summary>
        /// Enum RcodeServerFailure for value: RcodeServerFailure
        /// </summary>
        [EnumMember(Value = "RcodeServerFailure")]
        RcodeServerFailure = 3,

        /// <summary>
        /// Enum RcodeNameError for value: RcodeNameError
        /// </summary>
        [EnumMember(Value = "RcodeNameError")]
        RcodeNameError = 4,

        /// <summary>
        /// Enum RcodeNotImplemented for value: RcodeNotImplemented
        /// </summary>
        [EnumMember(Value = "RcodeNotImplemented")]
        RcodeNotImplemented = 5,

        /// <summary>
        /// Enum RcodeRefused for value: RcodeRefused
        /// </summary>
        [EnumMember(Value = "RcodeRefused")]
        RcodeRefused = 6,

        /// <summary>
        /// Enum RcodeYXDomain for value: RcodeYXDomain
        /// </summary>
        [EnumMember(Value = "RcodeYXDomain")]
        RcodeYXDomain = 7,

        /// <summary>
        /// Enum RcodeYXRrset for value: RcodeYXRrset
        /// </summary>
        [EnumMember(Value = "RcodeYXRrset")]
        RcodeYXRrset = 8,

        /// <summary>
        /// Enum RcodeNXRrset for value: RcodeNXRrset
        /// </summary>
        [EnumMember(Value = "RcodeNXRrset")]
        RcodeNXRrset = 9,

        /// <summary>
        /// Enum RcodeNotAuth for value: RcodeNotAuth
        /// </summary>
        [EnumMember(Value = "RcodeNotAuth")]
        RcodeNotAuth = 10,

        /// <summary>
        /// Enum RcodeNotZone for value: RcodeNotZone
        /// </summary>
        [EnumMember(Value = "RcodeNotZone")]
        RcodeNotZone = 11,

        /// <summary>
        /// Enum RcodeBadSig for value: RcodeBadSig
        /// </summary>
        [EnumMember(Value = "RcodeBadSig")]
        RcodeBadSig = 12,

        /// <summary>
        /// Enum RcodeBadVers for value: RcodeBadVers
        /// </summary>
        [EnumMember(Value = "RcodeBadVers")]
        RcodeBadVers = 13,

        /// <summary>
        /// Enum RcodeBadKey for value: RcodeBadKey
        /// </summary>
        [EnumMember(Value = "RcodeBadKey")]
        RcodeBadKey = 14,

        /// <summary>
        /// Enum RcodeBadTime for value: RcodeBadTime
        /// </summary>
        [EnumMember(Value = "RcodeBadTime")]
        RcodeBadTime = 15,

        /// <summary>
        /// Enum RcodeBadMode for value: RcodeBadMode
        /// </summary>
        [EnumMember(Value = "RcodeBadMode")]
        RcodeBadMode = 16,

        /// <summary>
        /// Enum RcodeBadName for value: RcodeBadName
        /// </summary>
        [EnumMember(Value = "RcodeBadName")]
        RcodeBadName = 17,

        /// <summary>
        /// Enum RcodeBadAlg for value: RcodeBadAlg
        /// </summary>
        [EnumMember(Value = "RcodeBadAlg")]
        RcodeBadAlg = 18,

        /// <summary>
        /// Enum RcodeBadTrunc for value: RcodeBadTrunc
        /// </summary>
        [EnumMember(Value = "RcodeBadTrunc")]
        RcodeBadTrunc = 19,

        /// <summary>
        /// Enum RcodeBadCookie for value: RcodeBadCookie
        /// </summary>
        [EnumMember(Value = "RcodeBadCookie")]
        RcodeBadCookie = 20
    }

}
