/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS server settings update request
    /// </summary>
    [DataContract(Name = "DNSServerSettingsUpdate")]
    public partial class DNSServerSettingsUpdate
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServerSettingsUpdate" /> class.
        /// </summary>
        /// <param name="accessSettings">accessSettings.</param>
        /// <param name="autoConnectDevicesEnabled">Whether to allow auto-connecting through link type.</param>
        /// <param name="blockChromePrefetch">Whether to block Google Chrome prefetch proxy.</param>
        /// <param name="blockFirefoxCanary">Whether Firefox Canary should be blocked.</param>
        /// <param name="blockPrivateRelay">Whether private relay should be blocked.</param>
        /// <param name="blockTtlSeconds">TTL for blocked request.</param>
        /// <param name="blockingModeSettings">blockingModeSettings.</param>
        /// <param name="filterListsSettings">filterListsSettings.</param>
        /// <param name="ipLogEnabled">Whether to log IP addresses of requests.</param>
        /// <param name="parentalControlSettings">parentalControlSettings.</param>
        /// <param name="protectionEnabled">Whether protection is enabled.</param>
        /// <param name="safebrowsingSettings">safebrowsingSettings.</param>
        /// <param name="userRulesSettings">userRulesSettings.</param>
        public DNSServerSettingsUpdate(DNSServerAccessSettingsUpdate accessSettings = default, bool autoConnectDevicesEnabled = default, bool blockChromePrefetch = default, bool blockFirefoxCanary = default, bool blockPrivateRelay = default, int blockTtlSeconds = default, BlockingModeSettingsUpdate blockingModeSettings = default, FilterListsSettingsUpdate filterListsSettings = default, bool ipLogEnabled = default, ParentalControlSettingsUpdate parentalControlSettings = default, bool protectionEnabled = default, SafebrowsingSettingsUpdate safebrowsingSettings = default, UserRulesSettingsUpdate userRulesSettings = default)
        {
            this.AccessSettings = accessSettings;
            this.AutoConnectDevicesEnabled = autoConnectDevicesEnabled;
            this.BlockChromePrefetch = blockChromePrefetch;
            this.BlockFirefoxCanary = blockFirefoxCanary;
            this.BlockPrivateRelay = blockPrivateRelay;
            this.BlockTtlSeconds = blockTtlSeconds;
            this.BlockingModeSettings = blockingModeSettings;
            this.FilterListsSettings = filterListsSettings;
            this.IpLogEnabled = ipLogEnabled;
            this.ParentalControlSettings = parentalControlSettings;
            this.ProtectionEnabled = protectionEnabled;
            this.SafebrowsingSettings = safebrowsingSettings;
            this.UserRulesSettings = userRulesSettings;
        }

        /// <summary>
        /// Gets or Sets AccessSettings
        /// </summary>
        [DataMember(Name = "access_settings", EmitDefaultValue = false)]
        public DNSServerAccessSettingsUpdate AccessSettings { get; set; }

        /// <summary>
        /// Whether to allow auto-connecting through link type
        /// </summary>
        /// <value>Whether to allow auto-connecting through link type</value>
        [DataMember(Name = "auto_connect_devices_enabled", EmitDefaultValue = true)]
        public bool AutoConnectDevicesEnabled { get; set; }

        /// <summary>
        /// Whether to block Google Chrome prefetch proxy
        /// </summary>
        /// <value>Whether to block Google Chrome prefetch proxy</value>
        [DataMember(Name = "block_chrome_prefetch", EmitDefaultValue = true)]
        public bool BlockChromePrefetch { get; set; }

        /// <summary>
        /// Whether Firefox Canary should be blocked
        /// </summary>
        /// <value>Whether Firefox Canary should be blocked</value>
        [DataMember(Name = "block_firefox_canary", EmitDefaultValue = true)]
        public bool BlockFirefoxCanary { get; set; }

        /// <summary>
        /// Whether private relay should be blocked
        /// </summary>
        /// <value>Whether private relay should be blocked</value>
        [DataMember(Name = "block_private_relay", EmitDefaultValue = true)]
        public bool BlockPrivateRelay { get; set; }

        /// <summary>
        /// TTL for blocked request
        /// </summary>
        /// <value>TTL for blocked request</value>
        /*
        <example>3600</example>
        */
        [DataMember(Name = "block_ttl_seconds", EmitDefaultValue = false)]
        public int BlockTtlSeconds { get; set; }

        /// <summary>
        /// Gets or Sets BlockingModeSettings
        /// </summary>
        [DataMember(Name = "blocking_mode_settings", EmitDefaultValue = false)]
        public BlockingModeSettingsUpdate BlockingModeSettings { get; set; }

        /// <summary>
        /// Gets or Sets FilterListsSettings
        /// </summary>
        [DataMember(Name = "filter_lists_settings", EmitDefaultValue = false)]
        public FilterListsSettingsUpdate FilterListsSettings { get; set; }

        /// <summary>
        /// Whether to log IP addresses of requests
        /// </summary>
        /// <value>Whether to log IP addresses of requests</value>
        [DataMember(Name = "ip_log_enabled", EmitDefaultValue = true)]
        public bool IpLogEnabled { get; set; }

        /// <summary>
        /// Gets or Sets ParentalControlSettings
        /// </summary>
        [DataMember(Name = "parental_control_settings", EmitDefaultValue = false)]
        public ParentalControlSettingsUpdate ParentalControlSettings { get; set; }

        /// <summary>
        /// Whether protection is enabled
        /// </summary>
        /// <value>Whether protection is enabled</value>
        [DataMember(Name = "protection_enabled", EmitDefaultValue = true)]
        public bool ProtectionEnabled { get; set; }

        /// <summary>
        /// Gets or Sets SafebrowsingSettings
        /// </summary>
        [DataMember(Name = "safebrowsing_settings", EmitDefaultValue = false)]
        public SafebrowsingSettingsUpdate SafebrowsingSettings { get; set; }

        /// <summary>
        /// Gets or Sets UserRulesSettings
        /// </summary>
        [DataMember(Name = "user_rules_settings", EmitDefaultValue = false)]
        public UserRulesSettingsUpdate UserRulesSettings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DNSServerSettingsUpdate {\n");
            sb.Append("  AccessSettings: ").Append(AccessSettings).Append("\n");
            sb.Append("  AutoConnectDevicesEnabled: ").Append(AutoConnectDevicesEnabled).Append("\n");
            sb.Append("  BlockChromePrefetch: ").Append(BlockChromePrefetch).Append("\n");
            sb.Append("  BlockFirefoxCanary: ").Append(BlockFirefoxCanary).Append("\n");
            sb.Append("  BlockPrivateRelay: ").Append(BlockPrivateRelay).Append("\n");
            sb.Append("  BlockTtlSeconds: ").Append(BlockTtlSeconds).Append("\n");
            sb.Append("  BlockingModeSettings: ").Append(BlockingModeSettings).Append("\n");
            sb.Append("  FilterListsSettings: ").Append(FilterListsSettings).Append("\n");
            sb.Append("  IpLogEnabled: ").Append(IpLogEnabled).Append("\n");
            sb.Append("  ParentalControlSettings: ").Append(ParentalControlSettings).Append("\n");
            sb.Append("  ProtectionEnabled: ").Append(ProtectionEnabled).Append("\n");
            sb.Append("  SafebrowsingSettings: ").Append(SafebrowsingSettings).Append("\n");
            sb.Append("  UserRulesSettings: ").Append(UserRulesSettings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
