/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS server access settings
    /// </summary>
    [DataContract(Name = "DNSServerAccessSettings")]
    public partial class DNSServerAccessSettings
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServerAccessSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DNSServerAccessSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServerAccessSettings" /> class.
        /// </summary>
        /// <param name="allowedClients">Allowed IP&#39;s, CIDR&#39;s or ASN&#39;s (required).</param>
        /// <param name="blockKnownScanners">Whether known scanners should be blocked (required).</param>
        /// <param name="blockedClients">Blocked IP&#39;s, CIDR&#39;s or ASN&#39;s (required).</param>
        /// <param name="blockedDomainRules">Blocked domain rules (required).</param>
        /// <param name="enabled">Whether access settings are enabled (required).</param>
        public DNSServerAccessSettings(List<string> allowedClients = default, bool blockKnownScanners = default, List<string> blockedClients = default, List<string> blockedDomainRules = default, bool enabled = default)
        {
            // to ensure "allowedClients" is required (not null)
            if (allowedClients == null)
            {
                throw new ArgumentNullException("allowedClients is a required property for DNSServerAccessSettings and cannot be null");
            }
            this.AllowedClients = allowedClients;
            this.BlockKnownScanners = blockKnownScanners;
            // to ensure "blockedClients" is required (not null)
            if (blockedClients == null)
            {
                throw new ArgumentNullException("blockedClients is a required property for DNSServerAccessSettings and cannot be null");
            }
            this.BlockedClients = blockedClients;
            // to ensure "blockedDomainRules" is required (not null)
            if (blockedDomainRules == null)
            {
                throw new ArgumentNullException("blockedDomainRules is a required property for DNSServerAccessSettings and cannot be null");
            }
            this.BlockedDomainRules = blockedDomainRules;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Allowed IP&#39;s, CIDR&#39;s or ASN&#39;s
        /// </summary>
        /// <value>Allowed IP&#39;s, CIDR&#39;s or ASN&#39;s</value>
        /*
        <example>[&quot;192.168.1.0/24&quot;]</example>
        */
        [DataMember(Name = "allowed_clients", IsRequired = true, EmitDefaultValue = true)]
        public List<string> AllowedClients { get; set; }

        /// <summary>
        /// Whether known scanners should be blocked
        /// </summary>
        /// <value>Whether known scanners should be blocked</value>
        [DataMember(Name = "block_known_scanners", IsRequired = true, EmitDefaultValue = true)]
        public bool BlockKnownScanners { get; set; }

        /// <summary>
        /// Blocked IP&#39;s, CIDR&#39;s or ASN&#39;s
        /// </summary>
        /// <value>Blocked IP&#39;s, CIDR&#39;s or ASN&#39;s</value>
        /*
        <example>[&quot;10.0.0.0/8&quot;]</example>
        */
        [DataMember(Name = "blocked_clients", IsRequired = true, EmitDefaultValue = true)]
        public List<string> BlockedClients { get; set; }

        /// <summary>
        /// Blocked domain rules
        /// </summary>
        /// <value>Blocked domain rules</value>
        /*
        <example>[&quot;example.org&quot;]</example>
        */
        [DataMember(Name = "blocked_domain_rules", IsRequired = true, EmitDefaultValue = true)]
        public List<string> BlockedDomainRules { get; set; }

        /// <summary>
        /// Whether access settings are enabled
        /// </summary>
        /// <value>Whether access settings are enabled</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DNSServerAccessSettings {\n");
            sb.Append("  AllowedClients: ").Append(AllowedClients).Append("\n");
            sb.Append("  BlockKnownScanners: ").Append(BlockKnownScanners).Append("\n");
            sb.Append("  BlockedClients: ").Append(BlockedClients).Append("\n");
            sb.Append("  BlockedDomainRules: ").Append(BlockedDomainRules).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
