/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS server
    /// </summary>
    [DataContract(Name = "DNSServer")]
    public partial class DNSServer
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServer" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DNSServer() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServer" /> class.
        /// </summary>
        /// <param name="varDefault">Whether this is the default DNS server (required).</param>
        /// <param name="deviceIds">Scheduled for removal in January 2027.</param>
        /// <param name="devicesCount">Connected devices count (required).</param>
        /// <param name="id">DNS server ID (required).</param>
        /// <param name="name">Name (required).</param>
        /// <param name="settings">settings (required).</param>
        public DNSServer(bool varDefault = default, List<string> deviceIds = default, int devicesCount = default, string id = default, string name = default, DNSServerSettings settings = default)
        {
            this.Default = varDefault;
            this.DevicesCount = devicesCount;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for DNSServer and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for DNSServer and cannot be null");
            }
            this.Name = name;
            // to ensure "settings" is required (not null)
            if (settings == null)
            {
                throw new ArgumentNullException("settings is a required property for DNSServer and cannot be null");
            }
            this.Settings = settings;
            this.DeviceIds = deviceIds;
        }

        /// <summary>
        /// Whether this is the default DNS server
        /// </summary>
        /// <value>Whether this is the default DNS server</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "default", IsRequired = true, EmitDefaultValue = true)]
        public bool Default { get; set; }

        /// <summary>
        /// Scheduled for removal in January 2027
        /// </summary>
        /// <value>Scheduled for removal in January 2027</value>
        [DataMember(Name = "device_ids", EmitDefaultValue = false)]
        [Obsolete]
        public List<string> DeviceIds { get; set; }

        /// <summary>
        /// Connected devices count
        /// </summary>
        /// <value>Connected devices count</value>
        /*
        <example>5</example>
        */
        [DataMember(Name = "devices_count", IsRequired = true, EmitDefaultValue = true)]
        public int DevicesCount { get; set; }

        /// <summary>
        /// DNS server ID
        /// </summary>
        /// <value>DNS server ID</value>
        /*
        <example>a9f29be1</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        /// <value>Name</value>
        /*
        <example>Main DNS server</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [DataMember(Name = "settings", IsRequired = true, EmitDefaultValue = true)]
        public DNSServerSettings Settings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DNSServer {\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("  DeviceIds: ").Append(DeviceIds).Append("\n");
            sb.Append("  DevicesCount: ").Append(DevicesCount).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
