/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Domain queries stats
    /// </summary>
    [DataContract(Name = "DomainQueriesStats")]
    public partial class DomainQueriesStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainQueriesStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DomainQueriesStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainQueriesStats" /> class.
        /// </summary>
        /// <param name="domain">Domain name (required).</param>
        /// <param name="value">value (required).</param>
        public DomainQueriesStats(string domain = default, QueriesStats value = default)
        {
            // to ensure "domain" is required (not null)
            if (domain == null)
            {
                throw new ArgumentNullException("domain is a required property for DomainQueriesStats and cannot be null");
            }
            this.Domain = domain;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for DomainQueriesStats and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// Domain name
        /// </summary>
        /// <value>Domain name</value>
        /*
        <example>facebook.com</example>
        */
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public QueriesStats Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DomainQueriesStats {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
