/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Fields errors
    /// </summary>
    [DataContract(Name = "FieldError")]
    public partial class FieldError
    {

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name = "error_code", IsRequired = true, EmitDefaultValue = true)]
        public ErrorCodes ErrorCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FieldError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FieldError" /> class.
        /// </summary>
        /// <param name="errorCode">errorCode (required).</param>
        /// <param name="field">Field name (required).</param>
        /// <param name="message">Error message.</param>
        public FieldError(ErrorCodes errorCode = default, string field = default, string message = default)
        {
            this.ErrorCode = errorCode;
            // to ensure "field" is required (not null)
            if (field == null)
            {
                throw new ArgumentNullException("field is a required property for FieldError and cannot be null");
            }
            this.Field = field;
            this.Message = message;
        }

        /// <summary>
        /// Field name
        /// </summary>
        /// <value>Field name</value>
        /*
        <example>name</example>
        */
        [DataMember(Name = "field", IsRequired = true, EmitDefaultValue = true)]
        public string Field { get; set; }

        /// <summary>
        /// Error message
        /// </summary>
        /// <value>Error message</value>
        /*
        <example>Field is required</example>
        */
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FieldError {\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
