/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// General filter list info
    /// </summary>
    [DataContract(Name = "FilterList")]
    public partial class FilterList
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterList" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FilterList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterList" /> class.
        /// </summary>
        /// <param name="categories">Filter categories (required).</param>
        /// <param name="description">Filter description (required).</param>
        /// <param name="downloadUrl">Filter download url (required).</param>
        /// <param name="filterId">Filter ID (required).</param>
        /// <param name="homepageUrl">Filter homepage url (required).</param>
        /// <param name="name">Filter name (required).</param>
        /// <param name="rulesCount">Rules count in filter (required).</param>
        /// <param name="sourceUrl">Filter source url (required).</param>
        /// <param name="tags">Filter tags (required).</param>
        /// <param name="timeUpdated">Filter last updated time (required).</param>
        public FilterList(List<FilterListCategory> categories = default, string description = default, string downloadUrl = default, string filterId = default, string homepageUrl = default, string name = default, int rulesCount = default, string sourceUrl = default, List<string> tags = default, DateTime timeUpdated = default)
        {
            // to ensure "categories" is required (not null)
            if (categories == null)
            {
                throw new ArgumentNullException("categories is a required property for FilterList and cannot be null");
            }
            this.Categories = categories;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for FilterList and cannot be null");
            }
            this.Description = description;
            // to ensure "downloadUrl" is required (not null)
            if (downloadUrl == null)
            {
                throw new ArgumentNullException("downloadUrl is a required property for FilterList and cannot be null");
            }
            this.DownloadUrl = downloadUrl;
            // to ensure "filterId" is required (not null)
            if (filterId == null)
            {
                throw new ArgumentNullException("filterId is a required property for FilterList and cannot be null");
            }
            this.FilterId = filterId;
            // to ensure "homepageUrl" is required (not null)
            if (homepageUrl == null)
            {
                throw new ArgumentNullException("homepageUrl is a required property for FilterList and cannot be null");
            }
            this.HomepageUrl = homepageUrl;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for FilterList and cannot be null");
            }
            this.Name = name;
            this.RulesCount = rulesCount;
            // to ensure "sourceUrl" is required (not null)
            if (sourceUrl == null)
            {
                throw new ArgumentNullException("sourceUrl is a required property for FilterList and cannot be null");
            }
            this.SourceUrl = sourceUrl;
            // to ensure "tags" is required (not null)
            if (tags == null)
            {
                throw new ArgumentNullException("tags is a required property for FilterList and cannot be null");
            }
            this.Tags = tags;
            this.TimeUpdated = timeUpdated;
        }

        /// <summary>
        /// Filter categories
        /// </summary>
        /// <value>Filter categories</value>
        [DataMember(Name = "categories", IsRequired = true, EmitDefaultValue = true)]
        public List<FilterListCategory> Categories { get; set; }

        /// <summary>
        /// Filter description
        /// </summary>
        /// <value>Filter description</value>
        /*
        <example>Filter composed of several other filters (AdGuard Base filter, Social Media filter)...</example>
        */
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Filter download url
        /// </summary>
        /// <value>Filter download url</value>
        /*
        <example>https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt</example>
        */
        [DataMember(Name = "download_url", IsRequired = true, EmitDefaultValue = true)]
        public string DownloadUrl { get; set; }

        /// <summary>
        /// Filter ID
        /// </summary>
        /// <value>Filter ID</value>
        /*
        <example>adguard_dns_filter</example>
        */
        [DataMember(Name = "filter_id", IsRequired = true, EmitDefaultValue = true)]
        public string FilterId { get; set; }

        /// <summary>
        /// Filter homepage url
        /// </summary>
        /// <value>Filter homepage url</value>
        /*
        <example>https://github.com/AdguardTeam/AdGuardSDNSFilter</example>
        */
        [DataMember(Name = "homepage_url", IsRequired = true, EmitDefaultValue = true)]
        public string HomepageUrl { get; set; }

        /// <summary>
        /// Filter name
        /// </summary>
        /// <value>Filter name</value>
        /*
        <example>AdGuard DNS filter</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Rules count in filter
        /// </summary>
        /// <value>Rules count in filter</value>
        /*
        <example>10000</example>
        */
        [DataMember(Name = "rules_count", IsRequired = true, EmitDefaultValue = true)]
        public int RulesCount { get; set; }

        /// <summary>
        /// Filter source url
        /// </summary>
        /// <value>Filter source url</value>
        /*
        <example>https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt</example>
        */
        [DataMember(Name = "source_url", IsRequired = true, EmitDefaultValue = true)]
        public string SourceUrl { get; set; }

        /// <summary>
        /// Filter tags
        /// </summary>
        /// <value>Filter tags</value>
        /*
        <example>[&quot;purpose:general&quot;]</example>
        */
        [DataMember(Name = "tags", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Filter last updated time
        /// </summary>
        /// <value>Filter last updated time</value>
        /*
        <example>2024-01-15T10:30Z</example>
        */
        [DataMember(Name = "time_updated", IsRequired = true, EmitDefaultValue = true)]
        public DateTime TimeUpdated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilterList {\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DownloadUrl: ").Append(DownloadUrl).Append("\n");
            sb.Append("  FilterId: ").Append(FilterId).Append("\n");
            sb.Append("  HomepageUrl: ").Append(HomepageUrl).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RulesCount: ").Append(RulesCount).Append("\n");
            sb.Append("  SourceUrl: ").Append(SourceUrl).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  TimeUpdated: ").Append(TimeUpdated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
