/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Filter list category type
    /// </summary>
    /// <value>Filter list category type</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FilterListCategoryType
    {
        /// <summary>
        /// Enum GENERAL for value: GENERAL
        /// </summary>
        [EnumMember(Value = "GENERAL")]
        GENERAL = 1,

        /// <summary>
        /// Enum SECURITY for value: SECURITY
        /// </summary>
        [EnumMember(Value = "SECURITY")]
        SECURITY = 2,

        /// <summary>
        /// Enum REGIONAL for value: REGIONAL
        /// </summary>
        [EnumMember(Value = "REGIONAL")]
        REGIONAL = 3,

        /// <summary>
        /// Enum OTHER for value: OTHER
        /// </summary>
        [EnumMember(Value = "OTHER")]
        OTHER = 4
    }

}
