/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Filter category info
    /// </summary>
    [DataContract(Name = "FilterListCategory")]
    public partial class FilterListCategory
    {

        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "category", IsRequired = true, EmitDefaultValue = true)]
        public FilterListCategoryType Category { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterListCategory" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FilterListCategory() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterListCategory" /> class.
        /// </summary>
        /// <param name="category">category (required).</param>
        /// <param name="description">Localized description (required).</param>
        /// <param name="value">Filter category value.</param>
        public FilterListCategory(FilterListCategoryType category = default, string description = default, string value = default)
        {
            this.Category = category;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for FilterListCategory and cannot be null");
            }
            this.Description = description;
            this.Value = value;
        }

        /// <summary>
        /// Localized description
        /// </summary>
        /// <value>Localized description</value>
        /*
        <example>Filters for security threats</example>
        */
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Filter category value
        /// </summary>
        /// <value>Filter category value</value>
        /*
        <example>security</example>
        */
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilterListCategory {\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
