/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// IP address info
    /// </summary>
    [DataContract(Name = "IpAddress")]
    public partial class IpAddress
    {

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public IpType Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="IpAddress" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected IpAddress() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="IpAddress" /> class.
        /// </summary>
        /// <param name="varIpAddress">IP address string (required).</param>
        /// <param name="type">type (required).</param>
        public IpAddress(string varIpAddress = default, IpType type = default)
        {
            // to ensure "varIpAddress" is required (not null)
            if (varIpAddress == null)
            {
                throw new ArgumentNullException("varIpAddress is a required property for IpAddress and cannot be null");
            }
            this.VarIpAddress = varIpAddress;
            this.Type = type;
        }

        /// <summary>
        /// IP address string
        /// </summary>
        /// <value>IP address string</value>
        /*
        <example>94.140.14.15</example>
        */
        [DataMember(Name = "ip_address", IsRequired = true, EmitDefaultValue = true)]
        public string VarIpAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IpAddress {\n");
            sb.Append("  VarIpAddress: ").Append(VarIpAddress).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
