/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Link dedicated IPv4 request
    /// </summary>
    [DataContract(Name = "LinkDedicatedIPv4")]
    public partial class LinkDedicatedIPv4
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkDedicatedIPv4" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LinkDedicatedIPv4() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkDedicatedIPv4" /> class.
        /// </summary>
        /// <param name="ip">Dedicated IPv4 (required).</param>
        public LinkDedicatedIPv4(string ip = default)
        {
            // to ensure "ip" is required (not null)
            if (ip == null)
            {
                throw new ArgumentNullException("ip is a required property for LinkDedicatedIPv4 and cannot be null");
            }
            this.Ip = ip;
        }

        /// <summary>
        /// Dedicated IPv4
        /// </summary>
        /// <value>Dedicated IPv4</value>
        /*
        <example>94.140.14.15</example>
        */
        [DataMember(Name = "ip", IsRequired = true, EmitDefaultValue = true)]
        public string Ip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LinkDedicatedIPv4 {\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
