/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Pagination page descriptor
    /// </summary>
    [DataContract(Name = "NavigationPage")]
    public partial class NavigationPage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationPage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NavigationPage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NavigationPage" /> class.
        /// </summary>
        /// <param name="pageCursor">Pagination cursor for this page (required).</param>
        /// <param name="pageNumber">Page number, positive (required).</param>
        public NavigationPage(string pageCursor = default, int pageNumber = default)
        {
            // to ensure "pageCursor" is required (not null)
            if (pageCursor == null)
            {
                throw new ArgumentNullException("pageCursor is a required property for NavigationPage and cannot be null");
            }
            this.PageCursor = pageCursor;
            this.PageNumber = pageNumber;
        }

        /// <summary>
        /// Pagination cursor for this page
        /// </summary>
        /// <value>Pagination cursor for this page</value>
        /*
        <example>MTY0NTQ1MTQxOTQ0MToxOjIwOjMxMTg&#x3D;</example>
        */
        [DataMember(Name = "page_cursor", IsRequired = true, EmitDefaultValue = true)]
        public string PageCursor { get; set; }

        /// <summary>
        /// Page number, positive
        /// </summary>
        /// <value>Page number, positive</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "page_number", IsRequired = true, EmitDefaultValue = true)]
        public int PageNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NavigationPage {\n");
            sb.Append("  PageCursor: ").Append(PageCursor).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
