/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Pagination
    /// </summary>
    [DataContract(Name = "Page")]
    public partial class Page
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Page" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Page() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Page" /> class.
        /// </summary>
        /// <param name="current">Whether this is the current page (required).</param>
        /// <param name="pageCursor">Pagination cursor (required).</param>
        /// <param name="pageNumber">Page number (required).</param>
        public Page(bool current = default, string pageCursor = default, int pageNumber = default)
        {
            this.Current = current;
            // to ensure "pageCursor" is required (not null)
            if (pageCursor == null)
            {
                throw new ArgumentNullException("pageCursor is a required property for Page and cannot be null");
            }
            this.PageCursor = pageCursor;
            this.PageNumber = pageNumber;
        }

        /// <summary>
        /// Whether this is the current page
        /// </summary>
        /// <value>Whether this is the current page</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "current", IsRequired = true, EmitDefaultValue = true)]
        public bool Current { get; set; }

        /// <summary>
        /// Pagination cursor
        /// </summary>
        /// <value>Pagination cursor</value>
        /*
        <example>1645451419441:1:20:3118</example>
        */
        [DataMember(Name = "page_cursor", IsRequired = true, EmitDefaultValue = true)]
        public string PageCursor { get; set; }

        /// <summary>
        /// Page number
        /// </summary>
        /// <value>Page number</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "page_number", IsRequired = true, EmitDefaultValue = true)]
        public int PageNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Page {\n");
            sb.Append("  Current: ").Append(Current).Append("\n");
            sb.Append("  PageCursor: ").Append(PageCursor).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
