/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Parental control filtering category
    /// </summary>
    [DataContract(Name = "ParentalControlFilteringCategory")]
    public partial class ParentalControlFilteringCategory
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParentalControlFilteringCategory" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ParentalControlFilteringCategory() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ParentalControlFilteringCategory" /> class.
        /// </summary>
        /// <param name="id">Category identifier (required).</param>
        public ParentalControlFilteringCategory(string id = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ParentalControlFilteringCategory and cannot be null");
            }
            this.Id = id;
        }

        /// <summary>
        /// Category identifier
        /// </summary>
        /// <value>Category identifier</value>
        /*
        <example>adult</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ParentalControlFilteringCategory {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
