/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Aggregated query counts
    /// </summary>
    [DataContract(Name = "QueriesStats")]
    public partial class QueriesStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueriesStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QueriesStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QueriesStats" /> class.
        /// </summary>
        /// <param name="blocked">Blocked queries count (required).</param>
        /// <param name="companies">Companies count (required).</param>
        /// <param name="queries">Overall queries count (required).</param>
        public QueriesStats(long blocked = default, int companies = default, long queries = default)
        {
            this.Blocked = blocked;
            this.Companies = companies;
            this.Queries = queries;
        }

        /// <summary>
        /// Blocked queries count
        /// </summary>
        /// <value>Blocked queries count</value>
        /*
        <example>14</example>
        */
        [DataMember(Name = "blocked", IsRequired = true, EmitDefaultValue = true)]
        public long Blocked { get; set; }

        /// <summary>
        /// Companies count
        /// </summary>
        /// <value>Companies count</value>
        /*
        <example>4</example>
        */
        [DataMember(Name = "companies", IsRequired = true, EmitDefaultValue = true)]
        public int Companies { get; set; }

        /// <summary>
        /// Overall queries count
        /// </summary>
        /// <value>Overall queries count</value>
        /*
        <example>86</example>
        */
        [DataMember(Name = "queries", IsRequired = true, EmitDefaultValue = true)]
        public long Queries { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueriesStats {\n");
            sb.Append("  Blocked: ").Append(Blocked).Append("\n");
            sb.Append("  Companies: ").Append(Companies).Append("\n");
            sb.Append("  Queries: ").Append(Queries).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
