/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Regular DNS proto type. Scheduled for removal: PLAIN_TCP, PLAIN_UDP
    /// </summary>
    /// <value>Regular DNS proto type. Scheduled for removal: PLAIN_TCP, PLAIN_UDP</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RegularDnsProtoType
    {
        /// <summary>
        /// Enum DNS for value: DNS
        /// </summary>
        [EnumMember(Value = "DNS")]
        DNS = 1,

        /// <summary>
        /// Enum PLAINTCP for value: PLAIN_TCP
        /// </summary>
        [EnumMember(Value = "PLAIN_TCP")]
        PLAINTCP = 2,

        /// <summary>
        /// Enum PLAINUDP for value: PLAIN_UDP
        /// </summary>
        [EnumMember(Value = "PLAIN_UDP")]
        PLAINUDP = 3
    }

}
