/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Safebrowsing settings
    /// </summary>
    [DataContract(Name = "SafebrowsingSettings")]
    public partial class SafebrowsingSettings
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SafebrowsingSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SafebrowsingSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SafebrowsingSettings" /> class.
        /// </summary>
        /// <param name="blockDangerousDomains">Whether filtering dangerous domains are enabled (required).</param>
        /// <param name="blockNrd">Whether filtering newly registered domains are enabled (required).</param>
        /// <param name="blockingModeSettings">blockingModeSettings (required).</param>
        /// <param name="enabled">Whether safebrowsing settings are enabled (required).</param>
        /// <param name="homoglyphProtectionEnabled">Whether homoglyph (IDN) protection is enabled (required).</param>
        /// <param name="typosquattingProtectionEnabled">Whether typosquatting protection is enabled (required).</param>
        public SafebrowsingSettings(bool blockDangerousDomains = default, bool blockNrd = default, BlockingModeSettings blockingModeSettings = default, bool enabled = default, bool homoglyphProtectionEnabled = default, bool typosquattingProtectionEnabled = default)
        {
            this.BlockDangerousDomains = blockDangerousDomains;
            this.BlockNrd = blockNrd;
            // to ensure "blockingModeSettings" is required (not null)
            if (blockingModeSettings == null)
            {
                throw new ArgumentNullException("blockingModeSettings is a required property for SafebrowsingSettings and cannot be null");
            }
            this.BlockingModeSettings = blockingModeSettings;
            this.Enabled = enabled;
            this.HomoglyphProtectionEnabled = homoglyphProtectionEnabled;
            this.TyposquattingProtectionEnabled = typosquattingProtectionEnabled;
        }

        /// <summary>
        /// Whether filtering dangerous domains are enabled
        /// </summary>
        /// <value>Whether filtering dangerous domains are enabled</value>
        [DataMember(Name = "block_dangerous_domains", IsRequired = true, EmitDefaultValue = true)]
        public bool BlockDangerousDomains { get; set; }

        /// <summary>
        /// Whether filtering newly registered domains are enabled
        /// </summary>
        /// <value>Whether filtering newly registered domains are enabled</value>
        [DataMember(Name = "block_nrd", IsRequired = true, EmitDefaultValue = true)]
        public bool BlockNrd { get; set; }

        /// <summary>
        /// Gets or Sets BlockingModeSettings
        /// </summary>
        [DataMember(Name = "blocking_mode_settings", IsRequired = true, EmitDefaultValue = true)]
        public BlockingModeSettings BlockingModeSettings { get; set; }

        /// <summary>
        /// Whether safebrowsing settings are enabled
        /// </summary>
        /// <value>Whether safebrowsing settings are enabled</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Whether homoglyph (IDN) protection is enabled
        /// </summary>
        /// <value>Whether homoglyph (IDN) protection is enabled</value>
        [DataMember(Name = "homoglyph_protection_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool HomoglyphProtectionEnabled { get; set; }

        /// <summary>
        /// Whether typosquatting protection is enabled
        /// </summary>
        /// <value>Whether typosquatting protection is enabled</value>
        [DataMember(Name = "typosquatting_protection_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool TyposquattingProtectionEnabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SafebrowsingSettings {\n");
            sb.Append("  BlockDangerousDomains: ").Append(BlockDangerousDomains).Append("\n");
            sb.Append("  BlockNrd: ").Append(BlockNrd).Append("\n");
            sb.Append("  BlockingModeSettings: ").Append(BlockingModeSettings).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  HomoglyphProtectionEnabled: ").Append(HomoglyphProtectionEnabled).Append("\n");
            sb.Append("  TyposquattingProtectionEnabled: ").Append(TyposquattingProtectionEnabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
