/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Describes a schedule for day
    /// </summary>
    [DataContract(Name = "ScheduleDay")]
    public partial class ScheduleDay
    {

        /// <summary>
        /// Gets or Sets DayOfWeek
        /// </summary>
        [DataMember(Name = "day_of_week", IsRequired = true, EmitDefaultValue = true)]
        public DayOfWeek DayOfWeek { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleDay" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduleDay() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleDay" /> class.
        /// </summary>
        /// <param name="dayOfWeek">dayOfWeek (required).</param>
        /// <param name="enabled">Shows enabled/disabled day (required).</param>
        /// <param name="fromTime">fromTime (required).</param>
        /// <param name="toTime">toTime (required).</param>
        public ScheduleDay(DayOfWeek dayOfWeek = default, bool enabled = default, ScheduleTime fromTime = default, ScheduleTime toTime = default)
        {
            this.DayOfWeek = dayOfWeek;
            this.Enabled = enabled;
            // to ensure "fromTime" is required (not null)
            if (fromTime == null)
            {
                throw new ArgumentNullException("fromTime is a required property for ScheduleDay and cannot be null");
            }
            this.FromTime = fromTime;
            // to ensure "toTime" is required (not null)
            if (toTime == null)
            {
                throw new ArgumentNullException("toTime is a required property for ScheduleDay and cannot be null");
            }
            this.ToTime = toTime;
        }

        /// <summary>
        /// Shows enabled/disabled day
        /// </summary>
        /// <value>Shows enabled/disabled day</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets FromTime
        /// </summary>
        [DataMember(Name = "from_time", IsRequired = true, EmitDefaultValue = true)]
        public ScheduleTime FromTime { get; set; }

        /// <summary>
        /// Gets or Sets ToTime
        /// </summary>
        [DataMember(Name = "to_time", IsRequired = true, EmitDefaultValue = true)]
        public ScheduleTime ToTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScheduleDay {\n");
            sb.Append("  DayOfWeek: ").Append(DayOfWeek).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  FromTime: ").Append(FromTime).Append("\n");
            sb.Append("  ToTime: ").Append(ToTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
