/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Describes a schedule for week
    /// </summary>
    [DataContract(Name = "ScheduleWeek")]
    public partial class ScheduleWeek
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleWeek" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduleWeek() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleWeek" /> class.
        /// </summary>
        /// <param name="dailySchedule">Schedule by days (required).</param>
        public ScheduleWeek(List<ScheduleDay> dailySchedule = default)
        {
            // to ensure "dailySchedule" is required (not null)
            if (dailySchedule == null)
            {
                throw new ArgumentNullException("dailySchedule is a required property for ScheduleWeek and cannot be null");
            }
            this.DailySchedule = dailySchedule;
        }

        /// <summary>
        /// Schedule by days
        /// </summary>
        /// <value>Schedule by days</value>
        [DataMember(Name = "daily_schedule", IsRequired = true, EmitDefaultValue = true)]
        public List<ScheduleDay> DailySchedule { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScheduleWeek {\n");
            sb.Append("  DailySchedule: ").Append(DailySchedule).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
