/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Secure DNS proto type. Scheduled for removal: DNSCRYPT_TCP, DNSCRYPT_UDP
    /// </summary>
    /// <value>Secure DNS proto type. Scheduled for removal: DNSCRYPT_TCP, DNSCRYPT_UDP</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SecureDnsProtoType
    {
        /// <summary>
        /// Enum DOH for value: DOH
        /// </summary>
        [EnumMember(Value = "DOH")]
        DOH = 1,

        /// <summary>
        /// Enum DOQ for value: DOQ
        /// </summary>
        [EnumMember(Value = "DOQ")]
        DOQ = 2,

        /// <summary>
        /// Enum DOT for value: DOT
        /// </summary>
        [EnumMember(Value = "DOT")]
        DOT = 3,

        /// <summary>
        /// Enum DNSCRYPT for value: DNSCRYPT
        /// </summary>
        [EnumMember(Value = "DNSCRYPT")]
        DNSCRYPT = 4,

        /// <summary>
        /// Enum DNSCRYPTTCP for value: DNSCRYPT_TCP
        /// </summary>
        [EnumMember(Value = "DNSCRYPT_TCP")]
        DNSCRYPTTCP = 5,

        /// <summary>
        /// Enum DNSCRYPTUDP for value: DNSCRYPT_UDP
        /// </summary>
        [EnumMember(Value = "DNSCRYPT_UDP")]
        DNSCRYPTUDP = 6
    }

}
