/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DevicesResponse : Paginated devices response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevicesResponse {
    /// List of devices
    #[serde(rename = "items")]
    pub items: Vec<models::Device>,
    #[serde(rename = "navigation")]
    pub navigation: Box<models::Navigation>,
}

impl DevicesResponse {
    /// Paginated devices response
    pub fn new(items: Vec<models::Device>, navigation: models::Navigation) -> DevicesResponse {
        DevicesResponse {
            items,
            navigation: Box::new(navigation),
        }
    }
}

