/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsServerUpdate : DNS server update request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsServerUpdate {
    /// DNS server name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl DnsServerUpdate {
    /// DNS server update request
    pub fn new() -> DnsServerUpdate {
        DnsServerUpdate {
            name: None,
        }
    }
}

