/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorCodes : Possible error codes
/// Possible error codes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCodes {
    #[serde(rename = "BAD_REQUEST")]
    BadRequest,
    #[serde(rename = "FIELD_REQUIRED")]
    FieldRequired,
    #[serde(rename = "FIELD_WRONG_VALUE")]
    FieldWrongValue,
    #[serde(rename = "FIELD_REACHED_LIMIT")]
    FieldReachedLimit,
    #[serde(rename = "ALREADY_EXISTS")]
    AlreadyExists,
    #[serde(rename = "INSUFFICIENT_LICENSE_TYPE")]
    InsufficientLicenseType,
    #[serde(rename = "RESOURCE_REACHED_LIMIT")]
    ResourceReachedLimit,
    #[serde(rename = "TOO_MANY_REQUESTS")]
    TooManyRequests,
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "CERT_DOMAIN_NAME")]
    CertDomainName,
    #[serde(rename = "CERT_SELF_SIGNED")]
    CertSelfSigned,
    #[serde(rename = "CERT_VALIDITY_DATE")]
    CertValidityDate,
    #[serde(rename = "ACCESS_FORBIDDEN")]
    AccessForbidden,
    #[serde(rename = "INVITATION_ALREADY_ADDED")]
    InvitationAlreadyAdded,
    #[serde(rename = "INVITATION_FOR_ACTIVE_MEMBER")]
    InvitationForActiveMember,
    #[serde(rename = "INVITATION_FOR_OWNER")]
    InvitationForOwner,
    #[serde(rename = "CUSTOM_FILTER_SOURCE_FORBIDDEN")]
    CustomFilterSourceForbidden,
    #[serde(rename = "CUSTOM_FILTER_SOURCE_UNREACHABLE")]
    CustomFilterSourceUnreachable,

}

impl std::fmt::Display for ErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BadRequest => write!(f, "BAD_REQUEST"),
            Self::FieldRequired => write!(f, "FIELD_REQUIRED"),
            Self::FieldWrongValue => write!(f, "FIELD_WRONG_VALUE"),
            Self::FieldReachedLimit => write!(f, "FIELD_REACHED_LIMIT"),
            Self::AlreadyExists => write!(f, "ALREADY_EXISTS"),
            Self::InsufficientLicenseType => write!(f, "INSUFFICIENT_LICENSE_TYPE"),
            Self::ResourceReachedLimit => write!(f, "RESOURCE_REACHED_LIMIT"),
            Self::TooManyRequests => write!(f, "TOO_MANY_REQUESTS"),
            Self::Unknown => write!(f, "UNKNOWN"),
            Self::CertDomainName => write!(f, "CERT_DOMAIN_NAME"),
            Self::CertSelfSigned => write!(f, "CERT_SELF_SIGNED"),
            Self::CertValidityDate => write!(f, "CERT_VALIDITY_DATE"),
            Self::AccessForbidden => write!(f, "ACCESS_FORBIDDEN"),
            Self::InvitationAlreadyAdded => write!(f, "INVITATION_ALREADY_ADDED"),
            Self::InvitationForActiveMember => write!(f, "INVITATION_FOR_ACTIVE_MEMBER"),
            Self::InvitationForOwner => write!(f, "INVITATION_FOR_OWNER"),
            Self::CustomFilterSourceForbidden => write!(f, "CUSTOM_FILTER_SOURCE_FORBIDDEN"),
            Self::CustomFilterSourceUnreachable => write!(f, "CUSTOM_FILTER_SOURCE_UNREACHABLE"),
        }
    }
}

impl Default for ErrorCodes {
    fn default() -> ErrorCodes {
        Self::BadRequest
    }
}

