/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterListsSettingsUpdate : Filter lists settings update
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterListsSettingsUpdate {
    /// Whether all filters are enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Filter list
    #[serde(rename = "filter_list", skip_serializing_if = "Option::is_none")]
    pub filter_list: Option<Vec<models::FilterListItemUpdate>>,
}

impl FilterListsSettingsUpdate {
    /// Filter lists settings update
    pub fn new() -> FilterListsSettingsUpdate {
        FilterListsSettingsUpdate {
            enabled: None,
            filter_list: None,
        }
    }
}

