/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NavigationPage : Pagination page descriptor
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NavigationPage {
    /// Pagination cursor for this page
    #[serde(rename = "page_cursor")]
    pub page_cursor: String,
    /// Page number, positive
    #[serde(rename = "page_number")]
    pub page_number: i32,
}

impl NavigationPage {
    /// Pagination page descriptor
    pub fn new(page_cursor: String, page_number: i32) -> NavigationPage {
        NavigationPage {
            page_cursor,
            page_number,
        }
    }
}

