/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParentalControlSettings : Parental control settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParentalControlSettings {
    /// Whether to block adult content
    #[serde(rename = "block_adult_websites_enabled")]
    pub block_adult_websites_enabled: bool,
    /// List of blocked services
    #[serde(rename = "blocked_services")]
    pub blocked_services: Vec<models::BlockedWebService>,
    /// Whether parental control is enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Whether to enforce safe search on supported search engines
    #[serde(rename = "engines_safe_search_enabled")]
    pub engines_safe_search_enabled: bool,
    #[serde(rename = "screen_time_schedule")]
    pub screen_time_schedule: Box<models::ScheduleWeek>,
    /// Whether to enforce safe search on YouTube
    #[serde(rename = "youtube_safe_search_enabled")]
    pub youtube_safe_search_enabled: bool,
}

impl ParentalControlSettings {
    /// Parental control settings
    pub fn new(block_adult_websites_enabled: bool, blocked_services: Vec<models::BlockedWebService>, enabled: bool, engines_safe_search_enabled: bool, screen_time_schedule: models::ScheduleWeek, youtube_safe_search_enabled: bool) -> ParentalControlSettings {
        ParentalControlSettings {
            block_adult_websites_enabled,
            blocked_services,
            enabled,
            engines_safe_search_enabled,
            screen_time_schedule: Box::new(screen_time_schedule),
            youtube_safe_search_enabled,
        }
    }
}

