/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserRulesSettingsUpdate : User rules update action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserRulesSettingsUpdate {
    /// Whether all rules are enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// List of rules
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<String>>,
}

impl UserRulesSettingsUpdate {
    /// User rules update action
    pub fn new() -> UserRulesSettingsUpdate {
        UserRulesSettingsUpdate {
            enabled: None,
            rules: None,
        }
    }
}

