#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Blocked Parental control Category queries stats

.PARAMETER Blocked
Blocked queries count
.PARAMETER Category
Category
.OUTPUTS

BlockedParentalCategoryQueriesStats<PSCustomObject>
#>

function Initialize-BlockedParentalCategoryQueriesStats {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${Blocked},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Category}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => BlockedParentalCategoryQueriesStats' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Blocked) {
            throw "invalid value for 'Blocked', 'Blocked' cannot be null."
        }

        if ($null -eq $Category) {
            throw "invalid value for 'Category', 'Category' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'blocked' = ${Blocked}
            'category' = ${Category}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to BlockedParentalCategoryQueriesStats<PSCustomObject>

.DESCRIPTION

Convert from JSON to BlockedParentalCategoryQueriesStats<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

BlockedParentalCategoryQueriesStats<PSCustomObject>
#>
function ConvertFrom-JsonToBlockedParentalCategoryQueriesStats {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => BlockedParentalCategoryQueriesStats' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BlockedParentalCategoryQueriesStats
        $AllProperties = ('blocked', 'category')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'blocked' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'blocked'))) {
            throw "Error! JSON cannot be serialized due to the required property 'blocked' missing."
        } else {
            $Blocked = $JsonParameters.PSobject.Properties['blocked'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'category'))) {
            throw "Error! JSON cannot be serialized due to the required property 'category' missing."
        } else {
            $Category = $JsonParameters.PSobject.Properties['category'].value
        }

        $PSO = [PSCustomObject]@{
            'blocked' = ${Blocked}
            'category' = ${Category}
        }

        return $PSO
    }

}

