#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Paginated devices response

.PARAMETER Items
List of devices
.PARAMETER Navigation
No description available.
.OUTPUTS

DevicesResponse<PSCustomObject>
#>

function Initialize-DevicesResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Items},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Navigation}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DevicesResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Items) {
            throw "invalid value for 'Items', 'Items' cannot be null."
        }

        if ($null -eq $Navigation) {
            throw "invalid value for 'Navigation', 'Navigation' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'items' = ${Items}
            'navigation' = ${Navigation}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DevicesResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to DevicesResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DevicesResponse<PSCustomObject>
#>
function ConvertFrom-JsonToDevicesResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DevicesResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DevicesResponse
        $AllProperties = ('items', 'navigation')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'items' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'items'))) {
            throw "Error! JSON cannot be serialized due to the required property 'items' missing."
        } else {
            $Items = $JsonParameters.PSobject.Properties['items'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'navigation'))) {
            throw "Error! JSON cannot be serialized due to the required property 'navigation' missing."
        } else {
            $Navigation = $JsonParameters.PSobject.Properties['navigation'].value
        }

        $PSO = [PSCustomObject]@{
            'items' = ${Items}
            'navigation' = ${Navigation}
        }

        return $PSO
    }

}

