#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum FilterListCategoryType.

.DESCRIPTION

Filter list category type
#>

enum FilterListCategoryType {
    # enum value: "GENERAL"
    GENERAL
    # enum value: "SECURITY"
    SECURITY
    # enum value: "REGIONAL"
    REGIONAL
    # enum value: "OTHER"
    OTHER
}

