/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlockedParentalCategoryQueriesStatsList : Blocked Parental control Category queries stats
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockedParentalCategoryQueriesStatsList {
    /// Stats for blocked Parental control Categories
    #[serde(rename = "stats")]
    pub stats: Vec<models::BlockedParentalCategoryQueriesStats>,
}

impl BlockedParentalCategoryQueriesStatsList {
    /// Blocked Parental control Category queries stats
    pub fn new(stats: Vec<models::BlockedParentalCategoryQueriesStats>) -> BlockedParentalCategoryQueriesStatsList {
        BlockedParentalCategoryQueriesStatsList {
            stats,
        }
    }
}

