/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CategoryQueriesStatsList : Category query statistics list
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryQueriesStatsList {
    /// List of queries stats
    #[serde(rename = "stats")]
    pub stats: Vec<models::CategoryQueriesStats>,
}

impl CategoryQueriesStatsList {
    /// Category query statistics list
    pub fn new(stats: Vec<models::CategoryQueriesStats>) -> CategoryQueriesStatsList {
        CategoryQueriesStatsList {
            stats,
        }
    }
}

