/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompanyDetailedQueriesStatsList : Company detailed queries statistics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyDetailedQueriesStatsList {
    #[serde(rename = "navigation")]
    pub navigation: Box<models::Navigation>,
    /// Pagination. Field is deprecated and scheduled for removal in January 2027. Use `navigation` instead
    #[serde(rename = "pages", skip_serializing_if = "Option::is_none")]
    pub pages: Option<Vec<models::Page>>,
    /// List of queries stats
    #[serde(rename = "stats")]
    pub stats: Vec<models::CompanyDetailedQueriesStats>,
}

impl CompanyDetailedQueriesStatsList {
    /// Company detailed queries statistics
    pub fn new(navigation: models::Navigation, stats: Vec<models::CompanyDetailedQueriesStats>) -> CompanyDetailedQueriesStatsList {
        CompanyDetailedQueriesStatsList {
            navigation: Box::new(navigation),
            pages: None,
            stats,
        }
    }
}

