/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceQueriesStatsList : Devices queries statistics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceQueriesStatsList {
    #[serde(rename = "navigation")]
    pub navigation: Box<models::Navigation>,
    /// List of queries stats
    #[serde(rename = "stats")]
    pub stats: Vec<models::DeviceQueriesStats>,
}

impl DeviceQueriesStatsList {
    /// Devices queries statistics
    pub fn new(navigation: models::Navigation, stats: Vec<models::DeviceQueriesStats>) -> DeviceQueriesStatsList {
        DeviceQueriesStatsList {
            navigation: Box::new(navigation),
            stats,
        }
    }
}

