/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceSettings : Device settings response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceSettings {
    /// Whether to use only DNS-over-HTTPS with authentication
    #[serde(rename = "detect_doh_auth_only")]
    pub detect_doh_auth_only: bool,
    /// Whether protection is enabled
    #[serde(rename = "protection_enabled")]
    pub protection_enabled: bool,
}

impl DeviceSettings {
    /// Device settings response
    pub fn new(detect_doh_auth_only: bool, protection_enabled: bool) -> DeviceSettings {
        DeviceSettings {
            detect_doh_auth_only,
            protection_enabled,
        }
    }
}

