/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsServersResponse : Paginated DNS servers response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsServersResponse {
    /// List of DNS servers
    #[serde(rename = "items")]
    pub items: Vec<models::DnsServer>,
    #[serde(rename = "navigation")]
    pub navigation: Box<models::Navigation>,
}

impl DnsServersResponse {
    /// Paginated DNS servers response
    pub fn new(items: Vec<models::DnsServer>, navigation: models::Navigation) -> DnsServersResponse {
        DnsServersResponse {
            items,
            navigation: Box::new(navigation),
        }
    }
}

