/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsServer : DNS server
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsServer {
    /// Whether this is the default DNS server
    #[serde(rename = "default")]
    pub default: bool,
    /// Scheduled for removal in January 2027
    #[serde(rename = "device_ids", skip_serializing_if = "Option::is_none")]
    pub device_ids: Option<Vec<String>>,
    /// Connected devices count
    #[serde(rename = "devices_count")]
    pub devices_count: i32,
    /// DNS server ID
    #[serde(rename = "id")]
    pub id: String,
    /// Name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "settings")]
    pub settings: Box<models::DnsServerSettings>,
}

impl DnsServer {
    /// DNS server
    pub fn new(default: bool, devices_count: i32, id: String, name: String, settings: models::DnsServerSettings) -> DnsServer {
        DnsServer {
            default,
            device_ids: None,
            devices_count,
            id,
            name,
            settings: Box::new(settings),
        }
    }
}

