/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DomainQueriesStatsList : Domains queries statistics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainQueriesStatsList {
    #[serde(rename = "navigation")]
    pub navigation: Box<models::Navigation>,
    /// List of queries stats
    #[serde(rename = "stats")]
    pub stats: Vec<models::DomainQueriesStats>,
}

impl DomainQueriesStatsList {
    /// Domains queries statistics
    pub fn new(navigation: models::Navigation, stats: Vec<models::DomainQueriesStats>) -> DomainQueriesStatsList {
        DomainQueriesStatsList {
            navigation: Box::new(navigation),
            stats,
        }
    }
}

