/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParentalControlFilteringCategory : Parental control filtering category
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParentalControlFilteringCategory {
    /// Category identifier
    #[serde(rename = "id")]
    pub id: String,
}

impl ParentalControlFilteringCategory {
    /// Parental control filtering category
    pub fn new(id: String) -> ParentalControlFilteringCategory {
        ParentalControlFilteringCategory {
            id,
        }
    }
}

