/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SafebrowsingSettingsUpdate : Safebrowsing settings update action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SafebrowsingSettingsUpdate {
    /// Whether filtering dangerous domains are enabled
    #[serde(rename = "block_dangerous_domains", skip_serializing_if = "Option::is_none")]
    pub block_dangerous_domains: Option<bool>,
    /// Whether filtering newly registered domains are enabled
    #[serde(rename = "block_nrd", skip_serializing_if = "Option::is_none")]
    pub block_nrd: Option<bool>,
    #[serde(rename = "blocking_mode_settings", skip_serializing_if = "Option::is_none")]
    pub blocking_mode_settings: Option<Box<models::BlockingModeSettingsUpdate>>,
    /// Whether safebrowsing settings are enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Whether homoglyph (IDN) protection is enabled
    #[serde(rename = "homoglyph_protection_enabled", skip_serializing_if = "Option::is_none")]
    pub homoglyph_protection_enabled: Option<bool>,
    /// Whether typosquatting protection is enabled
    #[serde(rename = "typosquatting_protection_enabled", skip_serializing_if = "Option::is_none")]
    pub typosquatting_protection_enabled: Option<bool>,
}

impl SafebrowsingSettingsUpdate {
    /// Safebrowsing settings update action
    pub fn new() -> SafebrowsingSettingsUpdate {
        SafebrowsingSettingsUpdate {
            block_dangerous_domains: None,
            block_nrd: None,
            blocking_mode_settings: None,
            enabled: None,
            homoglyph_protection_enabled: None,
            typosquatting_protection_enabled: None,
        }
    }
}

