/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SafebrowsingSettings : Safebrowsing settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SafebrowsingSettings {
    /// Whether filtering dangerous domains are enabled
    #[serde(rename = "block_dangerous_domains")]
    pub block_dangerous_domains: bool,
    /// Whether filtering newly registered domains are enabled
    #[serde(rename = "block_nrd")]
    pub block_nrd: bool,
    #[serde(rename = "blocking_mode_settings")]
    pub blocking_mode_settings: Box<models::BlockingModeSettings>,
    /// Whether safebrowsing settings are enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Whether homoglyph (IDN) protection is enabled
    #[serde(rename = "homoglyph_protection_enabled")]
    pub homoglyph_protection_enabled: bool,
    /// Whether typosquatting protection is enabled
    #[serde(rename = "typosquatting_protection_enabled")]
    pub typosquatting_protection_enabled: bool,
}

impl SafebrowsingSettings {
    /// Safebrowsing settings
    pub fn new(block_dangerous_domains: bool, block_nrd: bool, blocking_mode_settings: models::BlockingModeSettings, enabled: bool, homoglyph_protection_enabled: bool, typosquatting_protection_enabled: bool) -> SafebrowsingSettings {
        SafebrowsingSettings {
            block_dangerous_domains,
            block_nrd,
            blocking_mode_settings: Box::new(blocking_mode_settings),
            enabled,
            homoglyph_protection_enabled,
            typosquatting_protection_enabled,
        }
    }
}

