#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Blocked filtering category update action

.PARAMETER Enabled
Whether category blocking is enabled
.PARAMETER Id
Category identifier
.OUTPUTS

BlockedFilteringCategoryUpdate<PSCustomObject>
#>

function Initialize-BlockedFilteringCategoryUpdate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Enabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => BlockedFilteringCategoryUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($Id.length -gt 64) {
            throw "invalid value for 'Id', the character length must be smaller than or equal to 64."
        }

        if ($Id.length -lt 1) {
            throw "invalid value for 'Id', the character length must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            'enabled' = ${Enabled}
            'id' = ${Id}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to BlockedFilteringCategoryUpdate<PSCustomObject>

.DESCRIPTION

Convert from JSON to BlockedFilteringCategoryUpdate<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

BlockedFilteringCategoryUpdate<PSCustomObject>
#>
function ConvertFrom-JsonToBlockedFilteringCategoryUpdate {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => BlockedFilteringCategoryUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in BlockedFilteringCategoryUpdate
        $AllProperties = ('enabled', 'id')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'enabled'))) { #optional property not found
            $Enabled = $null
        } else {
            $Enabled = $JsonParameters.PSobject.Properties['enabled'].value
        }

        $PSO = [PSCustomObject]@{
            'enabled' = ${Enabled}
            'id' = ${Id}
        }

        return $PSO
    }

}

