#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

DNS server

.PARAMETER Default
Whether this is the default DNS server
.PARAMETER DeviceIds
Scheduled for removal in January 2027
.PARAMETER DevicesCount
Connected devices count
.PARAMETER Id
DNS server ID
.PARAMETER Name
Name
.PARAMETER Settings
No description available.
.OUTPUTS

DNSServer<PSCustomObject>
#>

function Initialize-DNSServer {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Default},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${DeviceIds},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${DevicesCount},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Settings}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DNSServer' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Default) {
            throw "invalid value for 'Default', 'Default' cannot be null."
        }

        if ($null -eq $DevicesCount) {
            throw "invalid value for 'DevicesCount', 'DevicesCount' cannot be null."
        }

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $Settings) {
            throw "invalid value for 'Settings', 'Settings' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'default' = ${Default}
            'device_ids' = ${DeviceIds}
            'devices_count' = ${DevicesCount}
            'id' = ${Id}
            'name' = ${Name}
            'settings' = ${Settings}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DNSServer<PSCustomObject>

.DESCRIPTION

Convert from JSON to DNSServer<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DNSServer<PSCustomObject>
#>
function ConvertFrom-JsonToDNSServer {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DNSServer' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DNSServer
        $AllProperties = ('default', 'device_ids', 'devices_count', 'id', 'name', 'settings')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'default' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'default'))) {
            throw "Error! JSON cannot be serialized due to the required property 'default' missing."
        } else {
            $Default = $JsonParameters.PSobject.Properties['default'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'devices_count'))) {
            throw "Error! JSON cannot be serialized due to the required property 'devices_count' missing."
        } else {
            $DevicesCount = $JsonParameters.PSobject.Properties['devices_count'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'id'))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties['id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'name'))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties['name'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'settings'))) {
            throw "Error! JSON cannot be serialized due to the required property 'settings' missing."
        } else {
            $Settings = $JsonParameters.PSobject.Properties['settings'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'device_ids'))) { #optional property not found
            $DeviceIds = $null
        } else {
            $DeviceIds = $JsonParameters.PSobject.Properties['device_ids'].value
        }

        $PSO = [PSCustomObject]@{
            'default' = ${Default}
            'device_ids' = ${DeviceIds}
            'devices_count' = ${DevicesCount}
            'id' = ${Id}
            'name' = ${Name}
            'settings' = ${Settings}
        }

        return $PSO
    }

}

