#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Domains queries statistics

.PARAMETER Navigation
No description available.
.PARAMETER Stats
List of queries stats
.OUTPUTS

DomainQueriesStatsList<PSCustomObject>
#>

function Initialize-DomainQueriesStatsList {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Navigation},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Stats}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DomainQueriesStatsList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Navigation) {
            throw "invalid value for 'Navigation', 'Navigation' cannot be null."
        }

        if ($null -eq $Stats) {
            throw "invalid value for 'Stats', 'Stats' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'navigation' = ${Navigation}
            'stats' = ${Stats}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DomainQueriesStatsList<PSCustomObject>

.DESCRIPTION

Convert from JSON to DomainQueriesStatsList<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DomainQueriesStatsList<PSCustomObject>
#>
function ConvertFrom-JsonToDomainQueriesStatsList {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DomainQueriesStatsList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DomainQueriesStatsList
        $AllProperties = ('navigation', 'stats')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'navigation' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'navigation'))) {
            throw "Error! JSON cannot be serialized due to the required property 'navigation' missing."
        } else {
            $Navigation = $JsonParameters.PSobject.Properties['navigation'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'stats'))) {
            throw "Error! JSON cannot be serialized due to the required property 'stats' missing."
        } else {
            $Stats = $JsonParameters.PSobject.Properties['stats'].value
        }

        $PSO = [PSCustomObject]@{
            'navigation' = ${Navigation}
            'stats' = ${Stats}
        }

        return $PSO
    }

}

