#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Pagination metadata

.PARAMETER Next
No description available.
.PARAMETER Prev
No description available.
.OUTPUTS

Navigation<PSCustomObject>
#>

function Initialize-Navigation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Next},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Prev}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => Navigation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            'next' = ${Next}
            'prev' = ${Prev}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Navigation<PSCustomObject>

.DESCRIPTION

Convert from JSON to Navigation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Navigation<PSCustomObject>
#>
function ConvertFrom-JsonToNavigation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => Navigation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Navigation
        $AllProperties = ('next', 'prev')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'next'))) { #optional property not found
            $Next = $null
        } else {
            $Next = $JsonParameters.PSobject.Properties['next'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'prev'))) { #optional property not found
            $Prev = $null
        } else {
            $Prev = $JsonParameters.PSobject.Properties['prev'].value
        }

        $PSO = [PSCustomObject]@{
            'next' = ${Next}
            'prev' = ${Prev}
        }

        return $PSO
    }

}

