#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Safebrowsing settings

.PARAMETER BlockDangerousDomains
Whether filtering dangerous domains are enabled
.PARAMETER BlockNrd
Whether filtering newly registered domains are enabled
.PARAMETER BlockingModeSettings
No description available.
.PARAMETER Enabled
Whether safebrowsing settings are enabled
.PARAMETER HomoglyphProtectionEnabled
Whether homoglyph (IDN) protection is enabled
.PARAMETER TyposquattingProtectionEnabled
Whether typosquatting protection is enabled
.OUTPUTS

SafebrowsingSettings<PSCustomObject>
#>

function Initialize-SafebrowsingSettings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${BlockDangerousDomains},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${BlockNrd},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${BlockingModeSettings},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Enabled},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${HomoglyphProtectionEnabled},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${TyposquattingProtectionEnabled}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => SafebrowsingSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $BlockDangerousDomains) {
            throw "invalid value for 'BlockDangerousDomains', 'BlockDangerousDomains' cannot be null."
        }

        if ($null -eq $BlockNrd) {
            throw "invalid value for 'BlockNrd', 'BlockNrd' cannot be null."
        }

        if ($null -eq $BlockingModeSettings) {
            throw "invalid value for 'BlockingModeSettings', 'BlockingModeSettings' cannot be null."
        }

        if ($null -eq $Enabled) {
            throw "invalid value for 'Enabled', 'Enabled' cannot be null."
        }

        if ($null -eq $HomoglyphProtectionEnabled) {
            throw "invalid value for 'HomoglyphProtectionEnabled', 'HomoglyphProtectionEnabled' cannot be null."
        }

        if ($null -eq $TyposquattingProtectionEnabled) {
            throw "invalid value for 'TyposquattingProtectionEnabled', 'TyposquattingProtectionEnabled' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'block_dangerous_domains' = ${BlockDangerousDomains}
            'block_nrd' = ${BlockNrd}
            'blocking_mode_settings' = ${BlockingModeSettings}
            'enabled' = ${Enabled}
            'homoglyph_protection_enabled' = ${HomoglyphProtectionEnabled}
            'typosquatting_protection_enabled' = ${TyposquattingProtectionEnabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SafebrowsingSettings<PSCustomObject>

.DESCRIPTION

Convert from JSON to SafebrowsingSettings<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SafebrowsingSettings<PSCustomObject>
#>
function ConvertFrom-JsonToSafebrowsingSettings {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => SafebrowsingSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SafebrowsingSettings
        $AllProperties = ('block_dangerous_domains', 'block_nrd', 'blocking_mode_settings', 'enabled', 'homoglyph_protection_enabled', 'typosquatting_protection_enabled')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'block_dangerous_domains' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'block_dangerous_domains'))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_dangerous_domains' missing."
        } else {
            $BlockDangerousDomains = $JsonParameters.PSobject.Properties['block_dangerous_domains'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'block_nrd'))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_nrd' missing."
        } else {
            $BlockNrd = $JsonParameters.PSobject.Properties['block_nrd'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'blocking_mode_settings'))) {
            throw "Error! JSON cannot be serialized due to the required property 'blocking_mode_settings' missing."
        } else {
            $BlockingModeSettings = $JsonParameters.PSobject.Properties['blocking_mode_settings'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'enabled'))) {
            throw "Error! JSON cannot be serialized due to the required property 'enabled' missing."
        } else {
            $Enabled = $JsonParameters.PSobject.Properties['enabled'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'homoglyph_protection_enabled'))) {
            throw "Error! JSON cannot be serialized due to the required property 'homoglyph_protection_enabled' missing."
        } else {
            $HomoglyphProtectionEnabled = $JsonParameters.PSobject.Properties['homoglyph_protection_enabled'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'typosquatting_protection_enabled'))) {
            throw "Error! JSON cannot be serialized due to the required property 'typosquatting_protection_enabled' missing."
        } else {
            $TyposquattingProtectionEnabled = $JsonParameters.PSobject.Properties['typosquatting_protection_enabled'].value
        }

        $PSO = [PSCustomObject]@{
            'block_dangerous_domains' = ${BlockDangerousDomains}
            'block_nrd' = ${BlockNrd}
            'blocking_mode_settings' = ${BlockingModeSettings}
            'enabled' = ${Enabled}
            'homoglyph_protection_enabled' = ${HomoglyphProtectionEnabled}
            'typosquatting_protection_enabled' = ${TyposquattingProtectionEnabled}
        }

        return $PSO
    }

}

