#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Safebrowsing settings update action

.PARAMETER BlockDangerousDomains
Whether filtering dangerous domains are enabled
.PARAMETER BlockNrd
Whether filtering newly registered domains are enabled
.PARAMETER BlockingModeSettings
No description available.
.PARAMETER Enabled
Whether safebrowsing settings are enabled
.PARAMETER HomoglyphProtectionEnabled
Whether homoglyph (IDN) protection is enabled
.PARAMETER TyposquattingProtectionEnabled
Whether typosquatting protection is enabled
.OUTPUTS

SafebrowsingSettingsUpdate<PSCustomObject>
#>

function Initialize-SafebrowsingSettingsUpdate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BlockDangerousDomains},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BlockNrd},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${BlockingModeSettings},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Enabled},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HomoglyphProtectionEnabled},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${TyposquattingProtectionEnabled}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => SafebrowsingSettingsUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            'block_dangerous_domains' = ${BlockDangerousDomains}
            'block_nrd' = ${BlockNrd}
            'blocking_mode_settings' = ${BlockingModeSettings}
            'enabled' = ${Enabled}
            'homoglyph_protection_enabled' = ${HomoglyphProtectionEnabled}
            'typosquatting_protection_enabled' = ${TyposquattingProtectionEnabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SafebrowsingSettingsUpdate<PSCustomObject>

.DESCRIPTION

Convert from JSON to SafebrowsingSettingsUpdate<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SafebrowsingSettingsUpdate<PSCustomObject>
#>
function ConvertFrom-JsonToSafebrowsingSettingsUpdate {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => SafebrowsingSettingsUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SafebrowsingSettingsUpdate
        $AllProperties = ('block_dangerous_domains', 'block_nrd', 'blocking_mode_settings', 'enabled', 'homoglyph_protection_enabled', 'typosquatting_protection_enabled')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'block_dangerous_domains'))) { #optional property not found
            $BlockDangerousDomains = $null
        } else {
            $BlockDangerousDomains = $JsonParameters.PSobject.Properties['block_dangerous_domains'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'block_nrd'))) { #optional property not found
            $BlockNrd = $null
        } else {
            $BlockNrd = $JsonParameters.PSobject.Properties['block_nrd'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'blocking_mode_settings'))) { #optional property not found
            $BlockingModeSettings = $null
        } else {
            $BlockingModeSettings = $JsonParameters.PSobject.Properties['blocking_mode_settings'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'enabled'))) { #optional property not found
            $Enabled = $null
        } else {
            $Enabled = $JsonParameters.PSobject.Properties['enabled'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'homoglyph_protection_enabled'))) { #optional property not found
            $HomoglyphProtectionEnabled = $null
        } else {
            $HomoglyphProtectionEnabled = $JsonParameters.PSobject.Properties['homoglyph_protection_enabled'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'typosquatting_protection_enabled'))) { #optional property not found
            $TyposquattingProtectionEnabled = $null
        } else {
            $TyposquattingProtectionEnabled = $JsonParameters.PSobject.Properties['typosquatting_protection_enabled'].value
        }

        $PSO = [PSCustomObject]@{
            'block_dangerous_domains' = ${BlockDangerousDomains}
            'block_nrd' = ${BlockNrd}
            'blocking_mode_settings' = ${BlockingModeSettings}
            'enabled' = ${Enabled}
            'homoglyph_protection_enabled' = ${HomoglyphProtectionEnabled}
            'typosquatting_protection_enabled' = ${TyposquattingProtectionEnabled}
        }

        return $PSO
    }

}

