#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DeviceQueriesStatsList' {
    Context 'DeviceQueriesStatsList' {
        It 'Initialize-DeviceQueriesStatsList' {
            # a simple test to create an object
            #$NewObject = Initialize-DeviceQueriesStatsList -Navigation "TEST_VALUE" -Stats "TEST_VALUE"
            #$NewObject | Should -BeOfType DeviceQueriesStatsList
            #$NewObject.property | Should -Be 0
        }
    }
}
