#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DevicesResponse' {
    Context 'DevicesResponse' {
        It 'Initialize-DevicesResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-DevicesResponse -Items "TEST_VALUE" -Navigation "TEST_VALUE"
            #$NewObject | Should -BeOfType DevicesResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
