#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DnsServersResponse' {
    Context 'DnsServersResponse' {
        It 'Initialize-DnsServersResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-DnsServersResponse -Items "TEST_VALUE" -Navigation "TEST_VALUE"
            #$NewObject | Should -BeOfType DnsServersResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
