#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DomainQueriesStatsList' {
    Context 'DomainQueriesStatsList' {
        It 'Initialize-DomainQueriesStatsList' {
            # a simple test to create an object
            #$NewObject = Initialize-DomainQueriesStatsList -Navigation "TEST_VALUE" -Stats "TEST_VALUE"
            #$NewObject | Should -BeOfType DomainQueriesStatsList
            #$NewObject.property | Should -Be 0
        }
    }
}
