#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'ParentalControlFilteringCategory' {
    Context 'ParentalControlFilteringCategory' {
        It 'Initialize-ParentalControlFilteringCategory' {
            # a simple test to create an object
            #$NewObject = Initialize-ParentalControlFilteringCategory -Id "TEST_VALUE"
            #$NewObject | Should -BeOfType ParentalControlFilteringCategory
            #$NewObject.property | Should -Be 0
        }
    }
}
