#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'AuthenticationApi' {
    Context 'Invoke-AccessToken' {
        It 'Test Invoke-AccessToken' {
            #$TestResult = Invoke-AccessToken -GrantType "TEST_VALUE" -ClientId "TEST_VALUE" -Code "TEST_VALUE" -CodeVerifier "TEST_VALUE" -MfaToken "TEST_VALUE" -Password "TEST_VALUE" -RedirectUri "TEST_VALUE" -RefreshToken "TEST_VALUE" -Username "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Authorize' {
        It 'Test Invoke-Authorize' {
            #$TestResult = Invoke-Authorize -ClientId "TEST_VALUE" -ResponseType "TEST_VALUE" -RedirectUri "TEST_VALUE" -State "TEST_VALUE" -Aid "TEST_VALUE" -Source "TEST_VALUE" -CodeChallenge "TEST_VALUE" -CodeChallengeMethod "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Revoke-Token' {
        It 'Test Revoke-Token' {
            #$TestResult = Revoke-Token -RefreshToken "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
