/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Access token error response
    /// </summary>
    [DataContract(Name = "AccessTokenErrorResponse")]
    public partial class AccessTokenErrorResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessTokenErrorResponse" /> class.
        /// </summary>
        /// <param name="error">Error type.</param>
        /// <param name="errorCode">Error code.</param>
        /// <param name="errorDescription">Error description.</param>
        public AccessTokenErrorResponse(string error = default, string errorCode = default, string errorDescription = default)
        {
            this.Error = error;
            this.ErrorCode = errorCode;
            this.ErrorDescription = errorDescription;
        }

        /// <summary>
        /// Error type
        /// </summary>
        /// <value>Error type</value>
        /*
        <example>unauthorized</example>
        */
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public string Error { get; set; }

        /// <summary>
        /// Error code
        /// </summary>
        /// <value>Error code</value>
        /*
        <example>2fa_required</example>
        */
        [DataMember(Name = "error_code", EmitDefaultValue = false)]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Error description
        /// </summary>
        /// <value>Error description</value>
        /*
        <example>2FA is required</example>
        */
        [DataMember(Name = "error_description", EmitDefaultValue = false)]
        public string ErrorDescription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccessTokenErrorResponse {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  ErrorDescription: ").Append(ErrorDescription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
