/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Blocked Parental control Category queries stats
    /// </summary>
    [DataContract(Name = "BlockedParentalCategoryQueriesStats")]
    public partial class BlockedParentalCategoryQueriesStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockedParentalCategoryQueriesStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BlockedParentalCategoryQueriesStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockedParentalCategoryQueriesStats" /> class.
        /// </summary>
        /// <param name="blocked">Blocked queries count (required).</param>
        /// <param name="category">Category (required).</param>
        public BlockedParentalCategoryQueriesStats(long blocked = default, string category = default)
        {
            this.Blocked = blocked;
            // to ensure "category" is required (not null)
            if (category == null)
            {
                throw new ArgumentNullException("category is a required property for BlockedParentalCategoryQueriesStats and cannot be null");
            }
            this.Category = category;
        }

        /// <summary>
        /// Blocked queries count
        /// </summary>
        /// <value>Blocked queries count</value>
        /*
        <example>14</example>
        */
        [DataMember(Name = "blocked", IsRequired = true, EmitDefaultValue = true)]
        public long Blocked { get; set; }

        /// <summary>
        /// Category
        /// </summary>
        /// <value>Category</value>
        /*
        <example>audio</example>
        */
        [DataMember(Name = "category", IsRequired = true, EmitDefaultValue = true)]
        public string Category { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BlockedParentalCategoryQueriesStats {\n");
            sb.Append("  Blocked: ").Append(Blocked).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
