/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Category type
    /// </summary>
    /// <value>Category type</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CategoryType
    {
        /// <summary>
        /// Enum ADS for value: ADS
        /// </summary>
        [EnumMember(Value = "ADS")]
        ADS = 1,

        /// <summary>
        /// Enum TRACKERS for value: TRACKERS
        /// </summary>
        [EnumMember(Value = "TRACKERS")]
        TRACKERS = 2,

        /// <summary>
        /// Enum SOCIALMEDIA for value: SOCIAL_MEDIA
        /// </summary>
        [EnumMember(Value = "SOCIAL_MEDIA")]
        SOCIALMEDIA = 3,

        /// <summary>
        /// Enum CDN for value: CDN
        /// </summary>
        [EnumMember(Value = "CDN")]
        CDN = 4,

        /// <summary>
        /// Enum OTHERS for value: OTHERS
        /// </summary>
        [EnumMember(Value = "OTHERS")]
        OTHERS = 5
    }

}
