/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Company detailed queries stats
    /// </summary>
    [DataContract(Name = "CompanyDetailedQueriesStats")]
    public partial class CompanyDetailedQueriesStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyDetailedQueriesStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CompanyDetailedQueriesStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CompanyDetailedQueriesStats" /> class.
        /// </summary>
        /// <param name="companyName">Company name (required).</param>
        /// <param name="domainsCount">Domains count (required).</param>
        /// <param name="topBlockedDomain">Top domain by blocked queries.</param>
        /// <param name="topQueriesDomain">Top domain by queries (required).</param>
        /// <param name="value">value (required).</param>
        public CompanyDetailedQueriesStats(string companyName = default, int domainsCount = default, string topBlockedDomain = default, string topQueriesDomain = default, QueriesStats value = default)
        {
            // to ensure "companyName" is required (not null)
            if (companyName == null)
            {
                throw new ArgumentNullException("companyName is a required property for CompanyDetailedQueriesStats and cannot be null");
            }
            this.CompanyName = companyName;
            this.DomainsCount = domainsCount;
            // to ensure "topQueriesDomain" is required (not null)
            if (topQueriesDomain == null)
            {
                throw new ArgumentNullException("topQueriesDomain is a required property for CompanyDetailedQueriesStats and cannot be null");
            }
            this.TopQueriesDomain = topQueriesDomain;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for CompanyDetailedQueriesStats and cannot be null");
            }
            this.Value = value;
            this.TopBlockedDomain = topBlockedDomain;
        }

        /// <summary>
        /// Company name
        /// </summary>
        /// <value>Company name</value>
        /*
        <example>Google</example>
        */
        [DataMember(Name = "company_name", IsRequired = true, EmitDefaultValue = true)]
        public string CompanyName { get; set; }

        /// <summary>
        /// Domains count
        /// </summary>
        /// <value>Domains count</value>
        /*
        <example>100</example>
        */
        [DataMember(Name = "domains_count", IsRequired = true, EmitDefaultValue = true)]
        public int DomainsCount { get; set; }

        /// <summary>
        /// Top domain by blocked queries
        /// </summary>
        /// <value>Top domain by blocked queries</value>
        /*
        <example>advertising.google.com</example>
        */
        [DataMember(Name = "top_blocked_domain", EmitDefaultValue = false)]
        public string TopBlockedDomain { get; set; }

        /// <summary>
        /// Top domain by queries
        /// </summary>
        /// <value>Top domain by queries</value>
        /*
        <example>ads.apple.com</example>
        */
        [DataMember(Name = "top_queries_domain", IsRequired = true, EmitDefaultValue = true)]
        public string TopQueriesDomain { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public QueriesStats Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CompanyDetailedQueriesStats {\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  DomainsCount: ").Append(DomainsCount).Append("\n");
            sb.Append("  TopBlockedDomain: ").Append(TopBlockedDomain).Append("\n");
            sb.Append("  TopQueriesDomain: ").Append(TopQueriesDomain).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
