/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Connect Device Type
    /// </summary>
    /// <value>Connect Device Type</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ConnectDeviceType
    {
        /// <summary>
        /// Enum WINDOWS for value: WINDOWS
        /// </summary>
        [EnumMember(Value = "WINDOWS")]
        WINDOWS = 1,

        /// <summary>
        /// Enum ANDROID for value: ANDROID
        /// </summary>
        [EnumMember(Value = "ANDROID")]
        ANDROID = 2,

        /// <summary>
        /// Enum MAC for value: MAC
        /// </summary>
        [EnumMember(Value = "MAC")]
        MAC = 3,

        /// <summary>
        /// Enum IOS for value: IOS
        /// </summary>
        [EnumMember(Value = "IOS")]
        IOS = 4,

        /// <summary>
        /// Enum LINUX for value: LINUX
        /// </summary>
        [EnumMember(Value = "LINUX")]
        LINUX = 5,

        /// <summary>
        /// Enum ROUTER for value: ROUTER
        /// </summary>
        [EnumMember(Value = "ROUTER")]
        ROUTER = 6,

        /// <summary>
        /// Enum SMARTTV for value: SMART_TV
        /// </summary>
        [EnumMember(Value = "SMART_TV")]
        SMARTTV = 7,

        /// <summary>
        /// Enum GAMECONSOLE for value: GAME_CONSOLE
        /// </summary>
        [EnumMember(Value = "GAME_CONSOLE")]
        GAMECONSOLE = 8,

        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN = 9
    }

}
