/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Dedicated IPs
    /// </summary>
    [DataContract(Name = "DedicatedIps")]
    public partial class DedicatedIps
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DedicatedIps" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DedicatedIps() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DedicatedIps" /> class.
        /// </summary>
        /// <param name="ipv4">Dedicated IPv4 address (required).</param>
        /// <param name="ipv4Limit">ipv4Limit (required).</param>
        /// <param name="ipv6">Dedicated IPv6 address (required).</param>
        public DedicatedIps(List<string> ipv4 = default, Limit ipv4Limit = default, List<string> ipv6 = default)
        {
            // to ensure "ipv4" is required (not null)
            if (ipv4 == null)
            {
                throw new ArgumentNullException("ipv4 is a required property for DedicatedIps and cannot be null");
            }
            this.Ipv4 = ipv4;
            // to ensure "ipv4Limit" is required (not null)
            if (ipv4Limit == null)
            {
                throw new ArgumentNullException("ipv4Limit is a required property for DedicatedIps and cannot be null");
            }
            this.Ipv4Limit = ipv4Limit;
            // to ensure "ipv6" is required (not null)
            if (ipv6 == null)
            {
                throw new ArgumentNullException("ipv6 is a required property for DedicatedIps and cannot be null");
            }
            this.Ipv6 = ipv6;
        }

        /// <summary>
        /// Dedicated IPv4 address
        /// </summary>
        /// <value>Dedicated IPv4 address</value>
        /*
        <example>[&quot;94.140.14.15&quot;]</example>
        */
        [DataMember(Name = "ipv4", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Ipv4 { get; set; }

        /// <summary>
        /// Gets or Sets Ipv4Limit
        /// </summary>
        [DataMember(Name = "ipv4_limit", IsRequired = true, EmitDefaultValue = true)]
        public Limit Ipv4Limit { get; set; }

        /// <summary>
        /// Dedicated IPv6 address
        /// </summary>
        /// <value>Dedicated IPv6 address</value>
        /*
        <example>[&quot;2a10:50c0::ad1:ff&quot;]</example>
        */
        [DataMember(Name = "ipv6", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Ipv6 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DedicatedIps {\n");
            sb.Append("  Ipv4: ").Append(Ipv4).Append("\n");
            sb.Append("  Ipv4Limit: ").Append(Ipv4Limit).Append("\n");
            sb.Append("  Ipv6: ").Append(Ipv6).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
