/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Device
    /// </summary>
    [DataContract(Name = "Device")]
    public partial class Device
    {

        /// <summary>
        /// Gets or Sets DeviceType
        /// </summary>
        [DataMember(Name = "device_type", IsRequired = true, EmitDefaultValue = true)]
        public ConnectDeviceType DeviceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Device" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Device() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Device" /> class.
        /// </summary>
        /// <param name="deviceType">deviceType (required).</param>
        /// <param name="dnsAddresses">dnsAddresses (required).</param>
        /// <param name="dnsServerId">DNS server ID (required).</param>
        /// <param name="id">Device ID (required).</param>
        /// <param name="name">Device name (required).</param>
        /// <param name="settings">settings (required).</param>
        public Device(ConnectDeviceType deviceType = default, DNSAddresses dnsAddresses = default, string dnsServerId = default, string id = default, string name = default, DeviceSettings settings = default)
        {
            this.DeviceType = deviceType;
            // to ensure "dnsAddresses" is required (not null)
            if (dnsAddresses == null)
            {
                throw new ArgumentNullException("dnsAddresses is a required property for Device and cannot be null");
            }
            this.DnsAddresses = dnsAddresses;
            // to ensure "dnsServerId" is required (not null)
            if (dnsServerId == null)
            {
                throw new ArgumentNullException("dnsServerId is a required property for Device and cannot be null");
            }
            this.DnsServerId = dnsServerId;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Device and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for Device and cannot be null");
            }
            this.Name = name;
            // to ensure "settings" is required (not null)
            if (settings == null)
            {
                throw new ArgumentNullException("settings is a required property for Device and cannot be null");
            }
            this.Settings = settings;
        }

        /// <summary>
        /// Gets or Sets DnsAddresses
        /// </summary>
        [DataMember(Name = "dns_addresses", IsRequired = true, EmitDefaultValue = true)]
        public DNSAddresses DnsAddresses { get; set; }

        /// <summary>
        /// DNS server ID
        /// </summary>
        /// <value>DNS server ID</value>
        /*
        <example>a9f29be1</example>
        */
        [DataMember(Name = "dns_server_id", IsRequired = true, EmitDefaultValue = true)]
        public string DnsServerId { get; set; }

        /// <summary>
        /// Device ID
        /// </summary>
        /// <value>Device ID</value>
        /*
        <example>b3e82cd1</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Device name
        /// </summary>
        /// <value>Device name</value>
        /*
        <example>My iphone</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [DataMember(Name = "settings", IsRequired = true, EmitDefaultValue = true)]
        public DeviceSettings Settings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Device {\n");
            sb.Append("  DeviceType: ").Append(DeviceType).Append("\n");
            sb.Append("  DnsAddresses: ").Append(DnsAddresses).Append("\n");
            sb.Append("  DnsServerId: ").Append(DnsServerId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
