/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Device queries stats
    /// </summary>
    [DataContract(Name = "DeviceQueriesStats")]
    public partial class DeviceQueriesStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceQueriesStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeviceQueriesStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceQueriesStats" /> class.
        /// </summary>
        /// <param name="deviceId">Device ID (required).</param>
        /// <param name="lastActivityTimeMillis">Last activity time in millis.</param>
        /// <param name="value">value (required).</param>
        public DeviceQueriesStats(string deviceId = default, long lastActivityTimeMillis = default, QueriesStats value = default)
        {
            // to ensure "deviceId" is required (not null)
            if (deviceId == null)
            {
                throw new ArgumentNullException("deviceId is a required property for DeviceQueriesStats and cannot be null");
            }
            this.DeviceId = deviceId;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for DeviceQueriesStats and cannot be null");
            }
            this.Value = value;
            this.LastActivityTimeMillis = lastActivityTimeMillis;
        }

        /// <summary>
        /// Device ID
        /// </summary>
        /// <value>Device ID</value>
        /*
        <example>b3e82cd1</example>
        */
        [DataMember(Name = "device_id", IsRequired = true, EmitDefaultValue = true)]
        public string DeviceId { get; set; }

        /// <summary>
        /// Last activity time in millis
        /// </summary>
        /// <value>Last activity time in millis</value>
        /*
        <example>1655804673000</example>
        */
        [DataMember(Name = "last_activity_time_millis", EmitDefaultValue = false)]
        public long LastActivityTimeMillis { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public QueriesStats Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeviceQueriesStats {\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  LastActivityTimeMillis: ").Append(LastActivityTimeMillis).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
