/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Device settings response
    /// </summary>
    [DataContract(Name = "DeviceSettings")]
    public partial class DeviceSettings
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeviceSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceSettings" /> class.
        /// </summary>
        /// <param name="detectDohAuthOnly">Whether to use only DNS-over-HTTPS with authentication (required).</param>
        /// <param name="protectionEnabled">Whether protection is enabled (required).</param>
        public DeviceSettings(bool detectDohAuthOnly = default, bool protectionEnabled = default)
        {
            this.DetectDohAuthOnly = detectDohAuthOnly;
            this.ProtectionEnabled = protectionEnabled;
        }

        /// <summary>
        /// Whether to use only DNS-over-HTTPS with authentication
        /// </summary>
        /// <value>Whether to use only DNS-over-HTTPS with authentication</value>
        [DataMember(Name = "detect_doh_auth_only", IsRequired = true, EmitDefaultValue = true)]
        public bool DetectDohAuthOnly { get; set; }

        /// <summary>
        /// Whether protection is enabled
        /// </summary>
        /// <value>Whether protection is enabled</value>
        [DataMember(Name = "protection_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool ProtectionEnabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeviceSettings {\n");
            sb.Append("  DetectDohAuthOnly: ").Append(DetectDohAuthOnly).Append("\n");
            sb.Append("  ProtectionEnabled: ").Append(ProtectionEnabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
