/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS protocol type
    /// </summary>
    [JsonConverter(typeof(DnsProtoTypeJsonConverter))]
    [DataContract(Name = "DnsProtoType")]
    public partial class DnsProtoType : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DnsProtoType" /> class
        /// with the <see cref="SecureDnsProtoType" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SecureDnsProtoType.</param>
        public DnsProtoType(SecureDnsProtoType actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DnsProtoType" /> class
        /// with the <see cref="RegularDnsProtoType" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RegularDnsProtoType.</param>
        public DnsProtoType(RegularDnsProtoType actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(RegularDnsProtoType) || value is RegularDnsProtoType)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SecureDnsProtoType) || value is SecureDnsProtoType)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: RegularDnsProtoType, SecureDnsProtoType");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `SecureDnsProtoType`. If the actual instance is not `SecureDnsProtoType`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SecureDnsProtoType</returns>
        public SecureDnsProtoType GetSecureDnsProtoType()
        {
            return (SecureDnsProtoType)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `RegularDnsProtoType`. If the actual instance is not `RegularDnsProtoType`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RegularDnsProtoType</returns>
        public RegularDnsProtoType GetRegularDnsProtoType()
        {
            return (RegularDnsProtoType)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DnsProtoType {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, DnsProtoType.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of DnsProtoType
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of DnsProtoType</returns>
        public static DnsProtoType FromJson(string jsonString)
        {
            DnsProtoType newDnsProtoType = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newDnsProtoType;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RegularDnsProtoType).GetProperty("AdditionalProperties") == null)
                {
                    newDnsProtoType = new DnsProtoType(JsonConvert.DeserializeObject<RegularDnsProtoType>(jsonString, DnsProtoType.SerializerSettings));
                }
                else
                {
                    newDnsProtoType = new DnsProtoType(JsonConvert.DeserializeObject<RegularDnsProtoType>(jsonString, DnsProtoType.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RegularDnsProtoType");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RegularDnsProtoType: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SecureDnsProtoType).GetProperty("AdditionalProperties") == null)
                {
                    newDnsProtoType = new DnsProtoType(JsonConvert.DeserializeObject<SecureDnsProtoType>(jsonString, DnsProtoType.SerializerSettings));
                }
                else
                {
                    newDnsProtoType = new DnsProtoType(JsonConvert.DeserializeObject<SecureDnsProtoType>(jsonString, DnsProtoType.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SecureDnsProtoType");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SecureDnsProtoType: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newDnsProtoType;
        }

    }

    /// <summary>
    /// Custom JSON converter for DnsProtoType
    /// </summary>
    public class DnsProtoTypeJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(DnsProtoType).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return DnsProtoType.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return DnsProtoType.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
