/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Paginated DNS servers response
    /// </summary>
    [DataContract(Name = "DnsServersResponse")]
    public partial class DnsServersResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DnsServersResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DnsServersResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DnsServersResponse" /> class.
        /// </summary>
        /// <param name="items">List of DNS servers (required).</param>
        /// <param name="navigation">navigation (required).</param>
        public DnsServersResponse(List<DNSServer> items = default, Navigation navigation = default)
        {
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for DnsServersResponse and cannot be null");
            }
            this.Items = items;
            // to ensure "navigation" is required (not null)
            if (navigation == null)
            {
                throw new ArgumentNullException("navigation is a required property for DnsServersResponse and cannot be null");
            }
            this.Navigation = navigation;
        }

        /// <summary>
        /// List of DNS servers
        /// </summary>
        /// <value>List of DNS servers</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<DNSServer> Items { get; set; }

        /// <summary>
        /// Gets or Sets Navigation
        /// </summary>
        [DataMember(Name = "navigation", IsRequired = true, EmitDefaultValue = true)]
        public Navigation Navigation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DnsServersResponse {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Navigation: ").Append(Navigation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
