/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS server access settings update
    /// </summary>
    [DataContract(Name = "DNSServerAccessSettingsUpdate")]
    public partial class DNSServerAccessSettingsUpdate
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServerAccessSettingsUpdate" /> class.
        /// </summary>
        /// <param name="allowedClients">Allowed IP&#39;s, CIDR&#39;s or ASN&#39;s.</param>
        /// <param name="blockKnownScanners">Whether known scanners should be blocked.</param>
        /// <param name="blockedClients">Blocked IP&#39;s, CIDR&#39;s or ASN&#39;s.</param>
        /// <param name="blockedDomainRules">Blocked domain rules.</param>
        /// <param name="enabled">Whether access settings are enabled.</param>
        public DNSServerAccessSettingsUpdate(List<string> allowedClients = default, bool blockKnownScanners = default, List<string> blockedClients = default, List<string> blockedDomainRules = default, bool enabled = default)
        {
            this.AllowedClients = allowedClients;
            this.BlockKnownScanners = blockKnownScanners;
            this.BlockedClients = blockedClients;
            this.BlockedDomainRules = blockedDomainRules;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Allowed IP&#39;s, CIDR&#39;s or ASN&#39;s
        /// </summary>
        /// <value>Allowed IP&#39;s, CIDR&#39;s or ASN&#39;s</value>
        /*
        <example>[&quot;192.168.1.0/24&quot;]</example>
        */
        [DataMember(Name = "allowed_clients", EmitDefaultValue = false)]
        public List<string> AllowedClients { get; set; }

        /// <summary>
        /// Whether known scanners should be blocked
        /// </summary>
        /// <value>Whether known scanners should be blocked</value>
        [DataMember(Name = "block_known_scanners", EmitDefaultValue = true)]
        public bool BlockKnownScanners { get; set; }

        /// <summary>
        /// Blocked IP&#39;s, CIDR&#39;s or ASN&#39;s
        /// </summary>
        /// <value>Blocked IP&#39;s, CIDR&#39;s or ASN&#39;s</value>
        /*
        <example>[&quot;10.0.0.0/8&quot;]</example>
        */
        [DataMember(Name = "blocked_clients", EmitDefaultValue = false)]
        public List<string> BlockedClients { get; set; }

        /// <summary>
        /// Blocked domain rules
        /// </summary>
        /// <value>Blocked domain rules</value>
        /*
        <example>[&quot;example.org&quot;]</example>
        */
        [DataMember(Name = "blocked_domain_rules", EmitDefaultValue = false)]
        public List<string> BlockedDomainRules { get; set; }

        /// <summary>
        /// Whether access settings are enabled
        /// </summary>
        /// <value>Whether access settings are enabled</value>
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DNSServerAccessSettingsUpdate {\n");
            sb.Append("  AllowedClients: ").Append(AllowedClients).Append("\n");
            sb.Append("  BlockKnownScanners: ").Append(BlockKnownScanners).Append("\n");
            sb.Append("  BlockedClients: ").Append(BlockedClients).Append("\n");
            sb.Append("  BlockedDomainRules: ").Append(BlockedDomainRules).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
