/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS server settings
    /// </summary>
    [DataContract(Name = "DNSServerSettings")]
    public partial class DNSServerSettings
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServerSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DNSServerSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServerSettings" /> class.
        /// </summary>
        /// <param name="accessSettings">accessSettings (required).</param>
        /// <param name="autoConnectDevicesEnabled">Whether to allow auto-connecting through link type (required).</param>
        /// <param name="blockChromePrefetch">Whether to block Google Chrome prefetch proxy (required).</param>
        /// <param name="blockFirefoxCanary">Whether Firefox Canary should be blocked (required).</param>
        /// <param name="blockPrivateRelay">Whether private relay should be blocked (required).</param>
        /// <param name="blockTtlSeconds">Blocked response TTL in seconds (required).</param>
        /// <param name="blockingModeSettings">blockingModeSettings (required).</param>
        /// <param name="filterListsSettings">filterListsSettings (required).</param>
        /// <param name="ipLogEnabled">Whether to log IP addresses of requests (required).</param>
        /// <param name="parentalControlSettings">parentalControlSettings (required).</param>
        /// <param name="protectionEnabled">Whether protection is enabled (required).</param>
        /// <param name="safebrowsingSettings">safebrowsingSettings (required).</param>
        /// <param name="userRulesSettings">userRulesSettings (required).</param>
        public DNSServerSettings(DNSServerAccessSettings accessSettings = default, bool autoConnectDevicesEnabled = default, bool blockChromePrefetch = default, bool blockFirefoxCanary = default, bool blockPrivateRelay = default, int blockTtlSeconds = default, BlockingModeSettings blockingModeSettings = default, FilterListsSettings filterListsSettings = default, bool ipLogEnabled = default, ParentalControlSettings parentalControlSettings = default, bool protectionEnabled = default, SafebrowsingSettings safebrowsingSettings = default, UserRulesSettings userRulesSettings = default)
        {
            // to ensure "accessSettings" is required (not null)
            if (accessSettings == null)
            {
                throw new ArgumentNullException("accessSettings is a required property for DNSServerSettings and cannot be null");
            }
            this.AccessSettings = accessSettings;
            this.AutoConnectDevicesEnabled = autoConnectDevicesEnabled;
            this.BlockChromePrefetch = blockChromePrefetch;
            this.BlockFirefoxCanary = blockFirefoxCanary;
            this.BlockPrivateRelay = blockPrivateRelay;
            this.BlockTtlSeconds = blockTtlSeconds;
            // to ensure "blockingModeSettings" is required (not null)
            if (blockingModeSettings == null)
            {
                throw new ArgumentNullException("blockingModeSettings is a required property for DNSServerSettings and cannot be null");
            }
            this.BlockingModeSettings = blockingModeSettings;
            // to ensure "filterListsSettings" is required (not null)
            if (filterListsSettings == null)
            {
                throw new ArgumentNullException("filterListsSettings is a required property for DNSServerSettings and cannot be null");
            }
            this.FilterListsSettings = filterListsSettings;
            this.IpLogEnabled = ipLogEnabled;
            // to ensure "parentalControlSettings" is required (not null)
            if (parentalControlSettings == null)
            {
                throw new ArgumentNullException("parentalControlSettings is a required property for DNSServerSettings and cannot be null");
            }
            this.ParentalControlSettings = parentalControlSettings;
            this.ProtectionEnabled = protectionEnabled;
            // to ensure "safebrowsingSettings" is required (not null)
            if (safebrowsingSettings == null)
            {
                throw new ArgumentNullException("safebrowsingSettings is a required property for DNSServerSettings and cannot be null");
            }
            this.SafebrowsingSettings = safebrowsingSettings;
            // to ensure "userRulesSettings" is required (not null)
            if (userRulesSettings == null)
            {
                throw new ArgumentNullException("userRulesSettings is a required property for DNSServerSettings and cannot be null");
            }
            this.UserRulesSettings = userRulesSettings;
        }

        /// <summary>
        /// Gets or Sets AccessSettings
        /// </summary>
        [DataMember(Name = "access_settings", IsRequired = true, EmitDefaultValue = true)]
        public DNSServerAccessSettings AccessSettings { get; set; }

        /// <summary>
        /// Whether to allow auto-connecting through link type
        /// </summary>
        /// <value>Whether to allow auto-connecting through link type</value>
        [DataMember(Name = "auto_connect_devices_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool AutoConnectDevicesEnabled { get; set; }

        /// <summary>
        /// Whether to block Google Chrome prefetch proxy
        /// </summary>
        /// <value>Whether to block Google Chrome prefetch proxy</value>
        [DataMember(Name = "block_chrome_prefetch", IsRequired = true, EmitDefaultValue = true)]
        public bool BlockChromePrefetch { get; set; }

        /// <summary>
        /// Whether Firefox Canary should be blocked
        /// </summary>
        /// <value>Whether Firefox Canary should be blocked</value>
        [DataMember(Name = "block_firefox_canary", IsRequired = true, EmitDefaultValue = true)]
        public bool BlockFirefoxCanary { get; set; }

        /// <summary>
        /// Whether private relay should be blocked
        /// </summary>
        /// <value>Whether private relay should be blocked</value>
        [DataMember(Name = "block_private_relay", IsRequired = true, EmitDefaultValue = true)]
        public bool BlockPrivateRelay { get; set; }

        /// <summary>
        /// Blocked response TTL in seconds
        /// </summary>
        /// <value>Blocked response TTL in seconds</value>
        /*
        <example>3600</example>
        */
        [DataMember(Name = "block_ttl_seconds", IsRequired = true, EmitDefaultValue = true)]
        public int BlockTtlSeconds { get; set; }

        /// <summary>
        /// Gets or Sets BlockingModeSettings
        /// </summary>
        [DataMember(Name = "blocking_mode_settings", IsRequired = true, EmitDefaultValue = true)]
        public BlockingModeSettings BlockingModeSettings { get; set; }

        /// <summary>
        /// Gets or Sets FilterListsSettings
        /// </summary>
        [DataMember(Name = "filter_lists_settings", IsRequired = true, EmitDefaultValue = true)]
        public FilterListsSettings FilterListsSettings { get; set; }

        /// <summary>
        /// Whether to log IP addresses of requests
        /// </summary>
        /// <value>Whether to log IP addresses of requests</value>
        [DataMember(Name = "ip_log_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool IpLogEnabled { get; set; }

        /// <summary>
        /// Gets or Sets ParentalControlSettings
        /// </summary>
        [DataMember(Name = "parental_control_settings", IsRequired = true, EmitDefaultValue = true)]
        public ParentalControlSettings ParentalControlSettings { get; set; }

        /// <summary>
        /// Whether protection is enabled
        /// </summary>
        /// <value>Whether protection is enabled</value>
        [DataMember(Name = "protection_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool ProtectionEnabled { get; set; }

        /// <summary>
        /// Gets or Sets SafebrowsingSettings
        /// </summary>
        [DataMember(Name = "safebrowsing_settings", IsRequired = true, EmitDefaultValue = true)]
        public SafebrowsingSettings SafebrowsingSettings { get; set; }

        /// <summary>
        /// Gets or Sets UserRulesSettings
        /// </summary>
        [DataMember(Name = "user_rules_settings", IsRequired = true, EmitDefaultValue = true)]
        public UserRulesSettings UserRulesSettings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DNSServerSettings {\n");
            sb.Append("  AccessSettings: ").Append(AccessSettings).Append("\n");
            sb.Append("  AutoConnectDevicesEnabled: ").Append(AutoConnectDevicesEnabled).Append("\n");
            sb.Append("  BlockChromePrefetch: ").Append(BlockChromePrefetch).Append("\n");
            sb.Append("  BlockFirefoxCanary: ").Append(BlockFirefoxCanary).Append("\n");
            sb.Append("  BlockPrivateRelay: ").Append(BlockPrivateRelay).Append("\n");
            sb.Append("  BlockTtlSeconds: ").Append(BlockTtlSeconds).Append("\n");
            sb.Append("  BlockingModeSettings: ").Append(BlockingModeSettings).Append("\n");
            sb.Append("  FilterListsSettings: ").Append(FilterListsSettings).Append("\n");
            sb.Append("  IpLogEnabled: ").Append(IpLogEnabled).Append("\n");
            sb.Append("  ParentalControlSettings: ").Append(ParentalControlSettings).Append("\n");
            sb.Append("  ProtectionEnabled: ").Append(ProtectionEnabled).Append("\n");
            sb.Append("  SafebrowsingSettings: ").Append(SafebrowsingSettings).Append("\n");
            sb.Append("  UserRulesSettings: ").Append(UserRulesSettings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
