/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Possible error codes
    /// </summary>
    /// <value>Possible error codes</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorCodes
    {
        /// <summary>
        /// Enum BADREQUEST for value: BAD_REQUEST
        /// </summary>
        [EnumMember(Value = "BAD_REQUEST")]
        BADREQUEST = 1,

        /// <summary>
        /// Enum FIELDREQUIRED for value: FIELD_REQUIRED
        /// </summary>
        [EnumMember(Value = "FIELD_REQUIRED")]
        FIELDREQUIRED = 2,

        /// <summary>
        /// Enum FIELDWRONGVALUE for value: FIELD_WRONG_VALUE
        /// </summary>
        [EnumMember(Value = "FIELD_WRONG_VALUE")]
        FIELDWRONGVALUE = 3,

        /// <summary>
        /// Enum FIELDREACHEDLIMIT for value: FIELD_REACHED_LIMIT
        /// </summary>
        [EnumMember(Value = "FIELD_REACHED_LIMIT")]
        FIELDREACHEDLIMIT = 4,

        /// <summary>
        /// Enum ALREADYEXISTS for value: ALREADY_EXISTS
        /// </summary>
        [EnumMember(Value = "ALREADY_EXISTS")]
        ALREADYEXISTS = 5,

        /// <summary>
        /// Enum INSUFFICIENTLICENSETYPE for value: INSUFFICIENT_LICENSE_TYPE
        /// </summary>
        [EnumMember(Value = "INSUFFICIENT_LICENSE_TYPE")]
        INSUFFICIENTLICENSETYPE = 6,

        /// <summary>
        /// Enum RESOURCEREACHEDLIMIT for value: RESOURCE_REACHED_LIMIT
        /// </summary>
        [EnumMember(Value = "RESOURCE_REACHED_LIMIT")]
        RESOURCEREACHEDLIMIT = 7,

        /// <summary>
        /// Enum TOOMANYREQUESTS for value: TOO_MANY_REQUESTS
        /// </summary>
        [EnumMember(Value = "TOO_MANY_REQUESTS")]
        TOOMANYREQUESTS = 8,

        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN = 9,

        /// <summary>
        /// Enum CERTDOMAINNAME for value: CERT_DOMAIN_NAME
        /// </summary>
        [EnumMember(Value = "CERT_DOMAIN_NAME")]
        CERTDOMAINNAME = 10,

        /// <summary>
        /// Enum CERTSELFSIGNED for value: CERT_SELF_SIGNED
        /// </summary>
        [EnumMember(Value = "CERT_SELF_SIGNED")]
        CERTSELFSIGNED = 11,

        /// <summary>
        /// Enum CERTVALIDITYDATE for value: CERT_VALIDITY_DATE
        /// </summary>
        [EnumMember(Value = "CERT_VALIDITY_DATE")]
        CERTVALIDITYDATE = 12,

        /// <summary>
        /// Enum ACCESSFORBIDDEN for value: ACCESS_FORBIDDEN
        /// </summary>
        [EnumMember(Value = "ACCESS_FORBIDDEN")]
        ACCESSFORBIDDEN = 13,

        /// <summary>
        /// Enum INVITATIONALREADYADDED for value: INVITATION_ALREADY_ADDED
        /// </summary>
        [EnumMember(Value = "INVITATION_ALREADY_ADDED")]
        INVITATIONALREADYADDED = 14,

        /// <summary>
        /// Enum INVITATIONFORACTIVEMEMBER for value: INVITATION_FOR_ACTIVE_MEMBER
        /// </summary>
        [EnumMember(Value = "INVITATION_FOR_ACTIVE_MEMBER")]
        INVITATIONFORACTIVEMEMBER = 15,

        /// <summary>
        /// Enum INVITATIONFOROWNER for value: INVITATION_FOR_OWNER
        /// </summary>
        [EnumMember(Value = "INVITATION_FOR_OWNER")]
        INVITATIONFOROWNER = 16,

        /// <summary>
        /// Enum CUSTOMFILTERSOURCEFORBIDDEN for value: CUSTOM_FILTER_SOURCE_FORBIDDEN
        /// </summary>
        [EnumMember(Value = "CUSTOM_FILTER_SOURCE_FORBIDDEN")]
        CUSTOMFILTERSOURCEFORBIDDEN = 17,

        /// <summary>
        /// Enum CUSTOMFILTERSOURCEUNREACHABLE for value: CUSTOM_FILTER_SOURCE_UNREACHABLE
        /// </summary>
        [EnumMember(Value = "CUSTOM_FILTER_SOURCE_UNREACHABLE")]
        CUSTOMFILTERSOURCEUNREACHABLE = 18
    }

}
