/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Filtering action source
    /// </summary>
    /// <value>Filtering action source</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FilteringActionSource
    {
        /// <summary>
        /// Enum FILTERS for value: FILTERS
        /// </summary>
        [EnumMember(Value = "FILTERS")]
        FILTERS = 1,

        /// <summary>
        /// Enum USERFILTER for value: USER_FILTER
        /// </summary>
        [EnumMember(Value = "USER_FILTER")]
        USERFILTER = 2,

        /// <summary>
        /// Enum SAFEBROWSING for value: SAFEBROWSING
        /// </summary>
        [EnumMember(Value = "SAFEBROWSING")]
        SAFEBROWSING = 3,

        /// <summary>
        /// Enum PARENTALSAFESEARCH for value: PARENTAL_SAFE_SEARCH
        /// </summary>
        [EnumMember(Value = "PARENTAL_SAFE_SEARCH")]
        PARENTALSAFESEARCH = 4,

        /// <summary>
        /// Enum PARENTALYOUTUBE for value: PARENTAL_YOUTUBE
        /// </summary>
        [EnumMember(Value = "PARENTAL_YOUTUBE")]
        PARENTALYOUTUBE = 5,

        /// <summary>
        /// Enum PARENTALADULT for value: PARENTAL_ADULT
        /// </summary>
        [EnumMember(Value = "PARENTAL_ADULT")]
        PARENTALADULT = 6,

        /// <summary>
        /// Enum PARENTALBLOCKEDSERVICE for value: PARENTAL_BLOCKED_SERVICE
        /// </summary>
        [EnumMember(Value = "PARENTAL_BLOCKED_SERVICE")]
        PARENTALBLOCKEDSERVICE = 7,

        /// <summary>
        /// Enum PARENTALFILTERINGCATEGORY for value: PARENTAL_FILTERING_CATEGORY
        /// </summary>
        [EnumMember(Value = "PARENTAL_FILTERING_CATEGORY")]
        PARENTALFILTERINGCATEGORY = 8,

        /// <summary>
        /// Enum PARENTALSCHEDULE for value: PARENTAL_SCHEDULE
        /// </summary>
        [EnumMember(Value = "PARENTAL_SCHEDULE")]
        PARENTALSCHEDULE = 9,

        /// <summary>
        /// Enum NEWLYREGISTEREDDOMAINS for value: NEWLY_REGISTERED_DOMAINS
        /// </summary>
        [EnumMember(Value = "NEWLY_REGISTERED_DOMAINS")]
        NEWLYREGISTEREDDOMAINS = 10,

        /// <summary>
        /// Enum TYPOSQUATTING for value: TYPOSQUATTING
        /// </summary>
        [EnumMember(Value = "TYPOSQUATTING")]
        TYPOSQUATTING = 11,

        /// <summary>
        /// Enum HOMOGLYPH for value: HOMOGLYPH
        /// </summary>
        [EnumMember(Value = "HOMOGLYPH")]
        HOMOGLYPH = 12
    }

}
