/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Filter lists settings
    /// </summary>
    [DataContract(Name = "FilterListsSettings")]
    public partial class FilterListsSettings
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterListsSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FilterListsSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterListsSettings" /> class.
        /// </summary>
        /// <param name="enabled">Whether all filters are enabled (required).</param>
        /// <param name="filterList">Filter list (required).</param>
        public FilterListsSettings(bool enabled = default, List<FilterListItem> filterList = default)
        {
            this.Enabled = enabled;
            // to ensure "filterList" is required (not null)
            if (filterList == null)
            {
                throw new ArgumentNullException("filterList is a required property for FilterListsSettings and cannot be null");
            }
            this.FilterList = filterList;
        }

        /// <summary>
        /// Whether all filters are enabled
        /// </summary>
        /// <value>Whether all filters are enabled</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Filter list
        /// </summary>
        /// <value>Filter list</value>
        [DataMember(Name = "filter_list", IsRequired = true, EmitDefaultValue = true)]
        public List<FilterListItem> FilterList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilterListsSettings {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  FilterList: ").Append(FilterList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
