/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Filtering action status
    /// </summary>
    /// <value>Filtering action status</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FilteringActionStatus
    {
        /// <summary>
        /// Enum UNKNOWN for value: UNKNOWN
        /// </summary>
        [EnumMember(Value = "UNKNOWN")]
        UNKNOWN,

        /// <summary>
        /// Enum NONE for value: NONE
        /// </summary>
        [EnumMember(Value = "NONE")]
        NONE,

        /// <summary>
        /// Enum REQUESTBLOCKED for value: REQUEST_BLOCKED
        /// </summary>
        [EnumMember(Value = "REQUEST_BLOCKED")]
        REQUESTBLOCKED,

        /// <summary>
        /// Enum RESPONSEBLOCKED for value: RESPONSE_BLOCKED
        /// </summary>
        [EnumMember(Value = "RESPONSE_BLOCKED")]
        RESPONSEBLOCKED,

        /// <summary>
        /// Enum REQUESTALLOWED for value: REQUEST_ALLOWED
        /// </summary>
        [EnumMember(Value = "REQUEST_ALLOWED")]
        REQUESTALLOWED,

        /// <summary>
        /// Enum RESPONSEALLOWED for value: RESPONSE_ALLOWED
        /// </summary>
        [EnumMember(Value = "RESPONSE_ALLOWED")]
        RESPONSEALLOWED,

        /// <summary>
        /// Enum MODIFIED for value: MODIFIED
        /// </summary>
        [EnumMember(Value = "MODIFIED")]
        MODIFIED
    }

}
