/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Filter
    /// </summary>
    [DataContract(Name = "FilterListItem")]
    public partial class FilterListItem
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterListItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FilterListItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterListItem" /> class.
        /// </summary>
        /// <param name="enabled">The flag that the filter is on or off (required).</param>
        /// <param name="filterId">Filter identifier (required).</param>
        public FilterListItem(bool enabled = default, string filterId = default)
        {
            this.Enabled = enabled;
            // to ensure "filterId" is required (not null)
            if (filterId == null)
            {
                throw new ArgumentNullException("filterId is a required property for FilterListItem and cannot be null");
            }
            this.FilterId = filterId;
        }

        /// <summary>
        /// The flag that the filter is on or off
        /// </summary>
        /// <value>The flag that the filter is on or off</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Filter identifier
        /// </summary>
        /// <value>Filter identifier</value>
        /*
        <example>adguard_dns_filter</example>
        */
        [DataMember(Name = "filter_id", IsRequired = true, EmitDefaultValue = true)]
        public string FilterId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilterListItem {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  FilterId: ").Append(FilterId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
