/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Query log response
    /// </summary>
    [DataContract(Name = "QueryLogResponse")]
    public partial class QueryLogResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryLogResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QueryLogResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryLogResponse" /> class.
        /// </summary>
        /// <param name="items">Query log items (required).</param>
        /// <param name="pages">Pagination (required).</param>
        public QueryLogResponse(List<QueryLogItem> items = default, List<Page> pages = default)
        {
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for QueryLogResponse and cannot be null");
            }
            this.Items = items;
            // to ensure "pages" is required (not null)
            if (pages == null)
            {
                throw new ArgumentNullException("pages is a required property for QueryLogResponse and cannot be null");
            }
            this.Pages = pages;
        }

        /// <summary>
        /// Query log items
        /// </summary>
        /// <value>Query log items</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<QueryLogItem> Items { get; set; }

        /// <summary>
        /// Pagination
        /// </summary>
        /// <value>Pagination</value>
        [DataMember(Name = "pages", IsRequired = true, EmitDefaultValue = true)]
        public List<Page> Pages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryLogResponse {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Pages: ").Append(Pages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
