/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Time moment query stats
    /// </summary>
    [DataContract(Name = "TimeQueriesStats")]
    public partial class TimeQueriesStats
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeQueriesStats" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TimeQueriesStats() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TimeQueriesStats" /> class.
        /// </summary>
        /// <param name="timeMillis">Time in millis (required).</param>
        /// <param name="value">value (required).</param>
        public TimeQueriesStats(long timeMillis = default, QueriesStats value = default)
        {
            this.TimeMillis = timeMillis;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for TimeQueriesStats and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// Time in millis
        /// </summary>
        /// <value>Time in millis</value>
        /*
        <example>1655804673</example>
        */
        [DataMember(Name = "time_millis", IsRequired = true, EmitDefaultValue = true)]
        public long TimeMillis { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public QueriesStats Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TimeQueriesStats {\n");
            sb.Append("  TimeMillis: ").Append(TimeMillis).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
