/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// User rules
    /// </summary>
    [DataContract(Name = "UserRulesSettings")]
    public partial class UserRulesSettings
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRulesSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserRulesSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserRulesSettings" /> class.
        /// </summary>
        /// <param name="enabled">Whether all rules are enabled (required).</param>
        /// <param name="rules">List of rules (required).</param>
        /// <param name="rulesCount">Rules count in user list (required).</param>
        public UserRulesSettings(bool enabled = default, List<string> rules = default, int rulesCount = default)
        {
            this.Enabled = enabled;
            // to ensure "rules" is required (not null)
            if (rules == null)
            {
                throw new ArgumentNullException("rules is a required property for UserRulesSettings and cannot be null");
            }
            this.Rules = rules;
            this.RulesCount = rulesCount;
        }

        /// <summary>
        /// Whether all rules are enabled
        /// </summary>
        /// <value>Whether all rules are enabled</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// List of rules
        /// </summary>
        /// <value>List of rules</value>
        /*
        <example>[&quot;||example.org^&quot;]</example>
        */
        [DataMember(Name = "rules", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Rules { get; set; }

        /// <summary>
        /// Rules count in user list
        /// </summary>
        /// <value>Rules count in user list</value>
        /*
        <example>50</example>
        */
        [DataMember(Name = "rules_count", IsRequired = true, EmitDefaultValue = true)]
        public int RulesCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserRulesSettings {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Rules: ").Append(Rules).Append("\n");
            sb.Append("  RulesCount: ").Append(RulesCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
