/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Web-service
    /// </summary>
    [DataContract(Name = "WebService")]
    public partial class WebService
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebService" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebService() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebService" /> class.
        /// </summary>
        /// <param name="iconSvg">SVG icon (required).</param>
        /// <param name="id">Web-service identifier (required).</param>
        /// <param name="name">Web-service name (required).</param>
        public WebService(string iconSvg = default, string id = default, string name = default)
        {
            // to ensure "iconSvg" is required (not null)
            if (iconSvg == null)
            {
                throw new ArgumentNullException("iconSvg is a required property for WebService and cannot be null");
            }
            this.IconSvg = iconSvg;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for WebService and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for WebService and cannot be null");
            }
            this.Name = name;
        }

        /// <summary>
        /// SVG icon
        /// </summary>
        /// <value>SVG icon</value>
        /*
        <example>&lt;svg&gt;&lt;path d&#x3D;&quot;M 44 14 C 44 13...&quot; /&gt;&lt;/svg&gt;</example>
        */
        [DataMember(Name = "icon_svg", IsRequired = true, EmitDefaultValue = true)]
        public string IconSvg { get; set; }

        /// <summary>
        /// Web-service identifier
        /// </summary>
        /// <value>Web-service identifier</value>
        /*
        <example>9gag</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Web-service name
        /// </summary>
        /// <value>Web-service name</value>
        /*
        <example>9GAG</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebService {\n");
            sb.Append("  IconSvg: ").Append(IconSvg).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
