#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'SafebrowsingSettingsUpdate' {
    Context 'SafebrowsingSettingsUpdate' {
        It 'Initialize-SafebrowsingSettingsUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-SafebrowsingSettingsUpdate -BlockDangerousDomains "TEST_VALUE" -BlockNrd "TEST_VALUE" -BlockingModeSettings "TEST_VALUE" -Enabled "TEST_VALUE" -HomoglyphProtectionEnabled "TEST_VALUE" -TyposquattingProtectionEnabled "TEST_VALUE"
            #$NewObject | Should -BeOfType SafebrowsingSettingsUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
