#
# AdGuard DNS API
# DNS API documentation
# Version: 1.15
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Issues an access token

.DESCRIPTION

No description available.

.PARAMETER GrantType
OAuth2 grant type. Accepted values: """"password"""", """"refresh_token"""", """"authorization_code"""". Required for Authorization Code + PKCE flow.

.PARAMETER ClientId
OAuth2 client identifier

.PARAMETER Code
Authorization code received from the authorization server

.PARAMETER CodeVerifier
PKCE code verifier (43-128 chars)

.PARAMETER MfaToken
Two-Factor authentication token (if enabled in account settings)

.PARAMETER Password
Account password

.PARAMETER RedirectUri
Redirect URI used in the authorization request

.PARAMETER RefreshToken
Refresh token

.PARAMETER Username
Account email

.PARAMETER ReturnType

Select the return type (optional): application/json, */*

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

AccessTokenResponse
#>
function Invoke-AccessToken {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${GrantType},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ClientId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Code},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${CodeVerifier},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${MfaToken},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Password},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${RedirectUri},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${RefreshToken},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Username},
        [String]
        [ValidateSet("application/json", "*/*")]
        $ReturnType,
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-AccessToken' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json', '*/*')

        if ($ReturnType) {
            # use the return type (MIME) provided by the user
            $LocalVarAccepts = @($ReturnType)
        }

        # HTTP header 'Content-Type'
        $LocalVarContentTypes = @('application/x-www-form-urlencoded')

        $LocalVarUri = '/oapi/v1/oauth_token'

        if ($ClientId) {
            $LocalVarFormParameters['client_id'] = $ClientId
        }

        if ($Code) {
            $LocalVarFormParameters['code'] = $Code
        }

        if ($CodeVerifier) {
            $LocalVarFormParameters['code_verifier'] = $CodeVerifier
        }

        if (!$GrantType) {
            throw "Error! The required parameter `GrantType` missing when calling accessToken."
        }
        $LocalVarFormParameters['grant_type'] = $GrantType

        if ($MfaToken) {
            $LocalVarFormParameters['mfa_token'] = $MfaToken
        }

        if ($Password) {
            $LocalVarFormParameters['password'] = $Password
        }

        if ($RedirectUri) {
            $LocalVarFormParameters['redirect_uri'] = $RedirectUri
        }

        if ($RefreshToken) {
            $LocalVarFormParameters['refresh_token'] = $RefreshToken
        }

        if ($Username) {
            $LocalVarFormParameters['username'] = $Username
        }

        $LocalVarResult = Invoke-ApiClient -Method 'POST' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "AccessTokenResponse" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

<#
.SYNOPSIS

Redirects to the authorization endpoint

.DESCRIPTION

No description available.

.PARAMETER ClientId
OAuth2 client identifier

.PARAMETER ResponseType
Type of grant. Use response_type=token for Implicit grant, response_type=code for Authorization Code + PKCE flow

.PARAMETER RedirectUri
A successful response results in a redirect to this URL

.PARAMETER State
An opaque value, used for security purposes

.PARAMETER Aid
Affiliate identifier

.PARAMETER Source
Affiliate source

.PARAMETER CodeChallenge
PKCE code challenge: BASE64URL(SHA256(code_verifier)). Required for Authorization Code + PKCE flow

.PARAMETER CodeChallengeMethod
PKCE challenge method. Only ""S256"" is supported

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

None
#>
function Invoke-Authorize {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ClientId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${ResponseType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${RedirectUri},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${State},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Aid},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${Source},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${CodeChallenge},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${CodeChallengeMethod},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Invoke-Authorize' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        $LocalVarUri = '/oapi/v1/oauth_authorize'

        if (!$ClientId) {
            throw "Error! The required parameter `ClientId` missing when calling authorize."
        }
        $LocalVarQueryParameters['client_id'] = $ClientId

        if (!$ResponseType) {
            throw "Error! The required parameter `ResponseType` missing when calling authorize."
        }
        $LocalVarQueryParameters['response_type'] = $ResponseType

        if (!$RedirectUri) {
            throw "Error! The required parameter `RedirectUri` missing when calling authorize."
        }
        $LocalVarQueryParameters['redirect_uri'] = $RedirectUri

        if ($State) {
            $LocalVarQueryParameters['state'] = $State
        }

        if ($Aid) {
            $LocalVarQueryParameters['aid'] = $Aid
        }

        if ($Source) {
            $LocalVarQueryParameters['source'] = $Source
        }

        if ($CodeChallenge) {
            $LocalVarQueryParameters['code_challenge'] = $CodeChallenge
        }

        if ($CodeChallengeMethod) {
            $LocalVarQueryParameters['code_challenge_method'] = $CodeChallengeMethod
        }

        $LocalVarResult = Invoke-ApiClient -Method 'GET' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

<#
.SYNOPSIS

Revokes a refresh token

.DESCRIPTION

No description available.

.PARAMETER RefreshToken
Refresh token to revoke

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

None
#>
function Revoke-Token {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${RefreshToken},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Revoke-Token' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        $LocalVarUri = '/oapi/v1/revoke_token'

        if (!$RefreshToken) {
            throw "Error! The required parameter `RefreshToken` missing when calling revokeToken."
        }
        $LocalVarQueryParameters['refresh_token'] = $RefreshToken

        $LocalVarResult = Invoke-ApiClient -Method 'POST' `
                                -Uri $LocalVarUri `
                                -Accepts $LocalVarAccepts `
                                -ContentTypes $LocalVarContentTypes `
                                -Body $LocalVarBodyParameter `
                                -HeaderParameters $LocalVarHeaderParameters `
                                -QueryParameters $LocalVarQueryParameters `
                                -FormParameters $LocalVarFormParameters `
                                -CookieParameters $LocalVarCookieParameters `
                                -ReturnType "" `
                                -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult["Response"]
        }
    }
}

